' Gambas module file

Public Function GetHTMLBodyRichText(sText As String) As String

  Dim xx As String
  Dim aa As Integer
  Dim yy As String

  xx = modString.GetSelectedText(sText, "<body", "</body>")
  aa = String.InStr(xx, ">")
  yy = Mid(xx, aa + 1)
  yy = Replace(yy, "</body>", "")

  Return Trim(yy)

End '

Public Function GetWebBodyRichText(sText As String) As String

  Dim xx As String
  Dim aa As Integer
  Dim yy As String
  Dim xval As String

  xx = modString.GetSelectedText(sText, "<body", "</body>")
  aa = String.InStr(xx, ">")
  yy = Mid(xx, aa + 1)
  yy = Replace(yy, "</body>", "")

  If modString.GetRichTextMode(yy) = True Then
    xval = Trim(yy)
  Else
    xval = "<span>" & Trim(yy) & "</span>"
  Endif

  Return xval

End '
