' Gambas module file

Public $appetcFolder As String
Public $appusrFolder As String
Public $appetcConfFile As String
Public $appetc7zFile As String
Public $appWebconfFile As String

Public AppName As String
Public AppDirectory As String
Public AppCacheDir As String
Public $htmlDirectory As String
Public $textDirectory As String
Public $docsDirectory As String
Public $localesDirectory As String
Public $mediaDirectory As String
Public $gnuDirectory As String
Public $scriptDirectory As String
Public $psppDirectory As String
Public $pythonDirectory As String
Public $templeteDirectory As String

Public $FIrstTimeSetting As Boolean
Public $ExistFixSetting As Boolean
Public $LogInCategory As String
Public $LogInGroup As String

Public $MACAddress As String
Public $localIP As String
Public $LogInTime As Date
Public $ApplKey As Integer

''--------------------------
Public $CryptValue As String
Public $CryptDBVal As String
Public $CryptZip As String
Public $CryptPDF As String

Public $CryptRepo As String
Public $CryptRepoZip As String
Public $SaltValue As String
Public $SysConfigPath As String

Public $HospitalName As String
Public $HospitalAddress As String
Public $Department As String
Public $HospLogo As String
Public $IRDLevel As String
Public $VATBill As String
Public $AutoRepoUpload As String
Public $AutoImgRepoUpload As String
Public $AllowInvoicePDF As String
Public $AllowInsecureDevice As String

Public $SysDataBase As String
Public $SysDisableDate As String
Public $SysDisableCharset As String
Public $SysCollation As String
Public $SysInterface As String
Private $SysUseSSL As Boolean
Public $SysLockOnDC As String

Public $SysMainService As String
Private $SysExtService As String
Private $SysFallService As String

Public $SysMainHost As String
Public $SysExtHost As String
Public $SysFallHost As String

Public $SysMainUser As String
Private $SysExtUser As String
Private $SysFallUser As String

Public $SysMainPassword As String
Private $SysExtPass As String
Private $SysFallPass As String

Public $SysMainPort As String
Private $SysExtPort As String
Private $SysFallPort As String

Public $SysFTPHost As String
Public $SysFTPFolder As String
Public $SysFTPUser As String
Public $SysFTPPass As String
Public $SysFTPSSL As String
Public $SysFTPCert As String
''------------------ END ------------------

Private $DBType As String
Private $DBHost As String
Private $DBName As String
Private $UserName As String
Private $UserPassword As String
Private $sPort As String

Public $conTarget As String

'NOTE: ------------------------------ File and Directory Functions -----------------------------
Public Sub MakeWorkingDir()

  AppName = Application.Name
  $appetcFolder = "/etc" &/ AppName
  $appusrFolder = "/usr/share" &/ AppName

  $appetcConfFile = $appetcFolder &/ AppName & ".conf"
  $appetc7zFile = $appetcFolder &/ AppName & ".conf.7z"
  $appWebconfFile = $appusrFolder &/ "web.conf"

  AppDirectory = Desktop.ConfigDir &/ AppName
  If Exist($appetcFolder &/ "appsettings.conf") Then
    $ExistFixSetting = True
  Else
    $ExistFixSetting = False
  Endif
  modSecure.SetGeneralCredentials()
  SetLocalDirectories()

End

Public Sub SetLocalDirectories()

  If Exist($appetcFolder &/ "html") Then
    $htmlDirectory = $appetcFolder &/ "html"
  Else
    $htmlDirectory = AppDirectory &/ "html"
  Endif
  If Exist($appetcFolder &/ "text") Then
    $textDirectory = $appetcFolder &/ "text"
  Else
    $textDirectory = AppDirectory &/ "text"
  Endif
  If Exist($appetcFolder &/ "docs") Then
    $docsDirectory = $appetcFolder &/ "docs"
  Else
    $docsDirectory = AppDirectory &/ "docs"
  Endif
  If Exist($appetcFolder &/ "locales") Then
    $localesDirectory = $appetcFolder &/ "locales"
  Else
    $localesDirectory = AppDirectory &/ "locales"
  Endif
  If Exist($appetcFolder &/ "media") Then
    $mediaDirectory = $appetcFolder &/ "media"
  Else
    $mediaDirectory = AppDirectory &/ "media"
  Endif
  If Exist($appetcFolder &/ "gnu") Then
    $gnuDirectory = $appetcFolder &/ "gnu"
  Else
    $gnuDirectory = AppDirectory &/ "gnu"
  Endif
  If Exist($appetcFolder &/ "pspp") Then
    $psppDirectory = $appetcFolder &/ "pspp"
  Else
    $psppDirectory = AppDirectory &/ "pspp"
  Endif
  If Exist($appetcFolder &/ "scripts") Then
    $scriptDirectory = $appetcFolder &/ "scripts"
  Else
    $scriptDirectory = AppDirectory &/ "scripts"
  Endif
  If Exist($appetcFolder &/ "python") Then
    $pythonDirectory = $appetcFolder &/ "python"
  Else
    $pythonDirectory = AppDirectory &/ "python"
  Endif
  $templeteDirectory = AppDirectory &/ "templates"

End

Public Sub CreateWorkingDir(sRefresh As Boolean)

  If Not Exist(modHelpVariable.AppDirectory) Then
    Mkdir modHelpVariable.AppDirectory
  Endif
  If Not Exist("/tmp" &/ AppName) Then
    Mkdir "/tmp" &/ AppName
  Endif
  If Not Exist(Desktop.CacheDir &/ modHelpVariable.AppName) Then
    Mkdir Desktop.CacheDir &/ modHelpVariable.AppName
  Endif

  If sRefresh = True Then
    If Exist(modHelpVariable.AppDirectory &/ "repository") Then
      Kill modHelpVariable.AppDirectory &/ "repository"
    Endif
    If Exist(modHelpVariable.AppDirectory &/ "current") Then
      Kill modHelpVariable.AppDirectory &/ "current"
    Endif
  Endif

  modExternal.CopyFromFolderToFolder(modHelpVariable.$appusrFolder, modHelpVariable.AppDirectory)
  If Not Exist(modHelpVariable.AppDirectory &/ "appsettings.conf") Then
    File.Save(modHelpVariable.AppDirectory &/ "appsettings.conf", "")
  Endif

End

Public Sub CreateUserCacheDir(sUser As String)

  AppCacheDir = "/tmp" &/ AppName &/ sUser
  If Not Exist(AppCacheDir) Then
    Mkdir AppCacheDir
  Endif

End

Public Sub SetAppConfigFile()

  If Exist(modHelpVariable.$appetcConfFile) Then
    modHelpVariable.$SysConfigPath = modHelpVariable.$appetcConfFile
  Else
    modHelpVariable.$SysConfigPath = modHelpVariable.$appetc7zFile
  Endif
  If MMain.$IsGUIApp = True Then
    Print "Configuration File is " & modHelpVariable.$SysConfigPath
  Endif

End

Public Sub SetApplicationGUI()

  If modBasic.$DebugDB = True Then
    db.Debug = True
  Endif
  modHelpVariable.CalenderConnection()
  modHelpVariable.ICDTablesConnection()
  modBasic.LoadGeneralVariables()
  If Exist(modHelpVariable.$appetcFolder &/ "sishrepository.conf.7z") Then
    CreateRepositoryLocal()
  Endif
  CreateLatestLocalDB()

End

'NOTE: -------------------------------- General Connection -------------------------------
Public Function GetConfigSettingFIle() As String

  Dim xfile As String
  Dim xCont As String

  xfile = Temp() & ".conf"
  If $SysConfigPath = modHelpVariable.$appetcConfFile Then
    xCont = File.Load(modHelpVariable.$appetcConfFile)
    File.Save(xfile, modReportVar.GetShellScriptValue(xCont))
  Else
    modDevAll.Get7ZExtraction(modHelpVariable.$appetc7zFile, $CryptZip, xfile)
  Endif
  Return xfile

End

Public Sub ReadConfigFile()

  Dim xlogo As String
  Dim xfile As String
  Dim xssl As String

  Dim xpolice As String
  Dim xformat As String
  Dim xdruginf As String

  xfile = GetConfigSettingFIle()
  $HospitalName = modControlSub.ShowSettingValue(xfile, "Hospital/Hospital")
  $HospitalAddress = modControlSub.ShowSettingValue(xfile, "Hospital/Address")
  $Department = modControlSub.ShowSettingValue(xfile, "Hospital/Department")
  modBasic.$compID = modControlSub.ShowSettingValue(xfile, "Hospital/ComputerID")
  $IRDLevel = modControlSub.ShowSettingValue(xfile, "Hospital/IRDCompliance")
  $VATBill = modControlSub.ShowSettingValue(xfile, "Hospital/VATRegistration")
  $AutoRepoUpload = modControlSub.ShowSettingValue(xfile, "Hospital/AutoRepositoryUpload")
  $AutoImgRepoUpload = modControlSub.ShowSettingValue(xfile, "Hospital/AutoImgRepositoryUpload")
  $AllowInvoicePDF = modControlSub.ShowSettingValue(xfile, "Hospital/AllowInvoicePDF")
  $AllowInsecureDevice = modControlSub.ShowSettingValue(xfile, "Hospital/AllowInsecureDevice")
  If MMain.$GovtApp = "Yes" Then
    If Exist(modHelpVariable.AppDirectory &/ "Nepal.png") Then
      Kill modHelpVariable.AppDirectory &/ "Nepal.png"
    Endif
    Copy "Nepal.png" To modHelpVariable.AppDirectory &/ "Nepal.png"
    $HospLogo = modHelpVariable.AppDirectory &/ "Nepal.png"
  Else
    xlogo = modControlSub.ShowSettingValue(xfile, "Hospital/Logo")
    If xlogo Then
      $HospLogo = xlogo
    Else
      $HospLogo = modHelpVariable.AppDirectory &/ "Logo.JPG"
    Endif
  Endif

  xpolice = modControlSub.ShowSettingValue(xfile, "Hospital/PoliceFormat")
  If xpolice = "Yes" Then
    MMain.$IsPolice = True
  Endif
  xformat = modControlSub.ShowSettingValue(xfile, "Hospital/CustomFormat")
  If xformat Then
    MMain.$CustomFormat = xformat
  Endif
  xdruginf = modControlSub.ShowSettingValue(xfile, "Hospital/DrugInformation")
  If xdruginf = "Yes" Then
    MMain.$IsDrugInfo = True
  Endif

  $SysDataBase = modControlSub.ShowSettingValue(xfile, "System/Database")
  $SysCollation = modControlSub.ShowSettingValue(xfile, "System/DBCollation")
  $SysInterface = modControlSub.ShowSettingValue(xfile, "System/NetInterface")
  $SysDisableDate = modControlSub.ShowSettingValue(xfile, "System/DisableDateCheck")
  $SysDisableCharset = modControlSub.ShowSettingValue(xfile, "System/DisableCharSet")
  xssl = modControlSub.ShowSettingValue(xfile, "System/UseOpenSSL")
  If xssl = "Yes" Then
    $SysUseSSL = True
  Else
    $SysUseSSL = False
  Endif
  $SysLockOnDC = modControlSub.ShowSettingValue(xfile, "System/LockOnDisconnect")

  $SysMainService = modControlSub.ShowSettingValue(xfile, "System/Service")
  $SysMainHost = modControlSub.ShowSettingValue(xfile, "System/Host")
  $SysMainUser = modControlSub.ShowSettingValue(xfile, "System/User")
  $SysMainPassword = modPassword.DecryptDBPass(modControlSub.ShowSettingValue(xfile, "System/Password"), $SysUseSSL)
  $SysMainPort = modControlSub.ShowSettingValue(xfile, "System/Port")

  $SysExtService = modControlSub.ShowSettingValue(xfile, "SystemExtra/Service")
  $SysExtHost = modControlSub.ShowSettingValue(xfile, "SystemExtra/Host")
  $SysExtUser = modControlSub.ShowSettingValue(xfile, "SystemExtra/User")
  $SysExtPass = modPassword.DecryptDBPass(modControlSub.ShowSettingValue(xfile, "SystemExtra/Password"), $SysUseSSL)
  $SysExtPort = modControlSub.ShowSettingValue(xfile, "SystemExtra/Port")

  $SysFallService = modControlSub.ShowSettingValue(xfile, "SystemFallback/Service")
  $SysFallHost = modControlSub.ShowSettingValue(xfile, "SystemFallback/Host")
  $SysFallUser = modControlSub.ShowSettingValue(xfile, "SystemFallback/User")
  $SysFallPass = modPassword.DecryptDBPass(modControlSub.ShowSettingValue(xfile, "SystemFallback/Password"), $SysUseSSL)
  $SysFallPort = modControlSub.ShowSettingValue(xfile, "SystemFallback/Port")

  $SysFTPHost = modControlSub.ShowSettingValue(xfile, "LocalFTP/Host")
  $SysFTPFolder = modControlSub.ShowSettingValue(xfile, "LocalFTP/Folder")
  $SysFTPUser = modControlSub.ShowSettingValue(xfile, "LocalFTP/User")
  $SysFTPPass = modPassword.DecryptDBPass(modControlSub.ShowSettingValue(xfile, "LocalFTP/Password"), $SysUseSSL)
  $SysFTPSSL = modControlSub.ShowSettingValue(xfile, "LocalFTP/EnableSSL")
  $SysFTPCert = modControlSub.ShowSettingValue(xfile, "LocalFTP/Certificate")

  Try Kill xfile

End

Public Sub CalenderConnection()

  modDatabase.$calConn = modDBApp.OpenConnection("sqlite3", modHelpVariable.$docsDirectory, "calender", "", "")
  If modDatabase.$calConn.Opened = True Then
    modBasic.DebugString("App connected to calendar sqlite database. Database Driver: " & CStr(modDatabase.$calConn.Version))
  Endif

End

Public Sub ICDTablesConnection()

  modDatabase.$icdConn = modDBApp.OpenConnection("sqlite3", modHelpVariable.$docsDirectory, "icdtables", "", "")
  If modDatabase.$icdConn.Opened = True Then
    modBasic.DebugString("App connected to ICD sqlite database. Database Driver: " & CStr(modDatabase.$icdConn.Version))
  Endif

End

Public Sub ConnectionMain()

  ReadConfigFile()
  $conTarget = modSettings.ShowSettingFromFIle("SISH_Connection/ConnectionType")
  If $conTarget = "Remote" Then
    $DBType = modSettings.ShowSettingFromFIle("SISH_Connection/RemoteService")
    $DBHost = modSettings.ShowSettingFromFIle("SISH_Connection/RemoteHost")
    $DBName = modSettings.ShowSettingFromFIle("SISH_Connection/RemoteDatabase")
    $UserName = UnBase64(modSettings.ShowSettingFromFIle("SISH_Connection/RemoteUser"))
    $UserPassword = UnBase64(modSettings.ShowSettingFromFIle("SISH_Connection/RemotePass"))
    $sPort = modSettings.ShowSettingFromFIle("SISH_Connection/RemotePort")
  Else
    $DBType = $SysMainService
    $DBHost = $SysMainHost
    $DBName = $SysDataBase
    $UserName = $SysMainUser
    $UserPassword = $SysMainPassword
    $sPort = $SysMainPort
  Endif

  If $sPort Then
    modDatabase.$myConn = modDBApp.OpenConnection($DBType, $DBHost, $DBName, $UserName, $UserPassword, $sPort)
  Else
    modDatabase.$myConn = modDBApp.OpenConnection($DBType, $DBHost, $DBName, $UserName, $UserPassword)
  Endif

  If modDatabase.$myConn.Opened = True Then
    modBasic.DebugString("App connected to " & $DBName & " on Main Server at " & $DBHost & " . Database Driver: " & CStr(modDatabase.$myConn.Version))
    ConnectionExtra()
  Else
    If $conTarget = "Remote" Then
    Else
      modBasic.DebugString("Unable to connect " & $DBName & " on Main Server at " & $DBHost & " . Attempting to connect Fallback Server.")
      ConnectionFallBack()
    Endif
  Endif
  ''medical connection
  modDatabase.$medConn = modDatabase.$myConn

End

Private Sub ConnectionFallBack()

  Dim UserName As String
  Dim UserPassword As String
  Dim DBName As String
  Dim DBType As String
  Dim DBHost As String
  Dim sPort As String

  DBName = $SysDataBase
  DBType = $SysFallService
  DBHost = $SysFallHost
  UserName = $SysFallUser
  UserPassword = $SysFallPass
  sPort = $SysFallPort

  If sPort Then
    modDatabase.$myConn = modDBApp.OpenConnection(DBType, DBHost, DBName, UserName, UserPassword, sPort)
  Else
    modDatabase.$myConn = modDBApp.OpenConnection(DBType, DBHost, DBName, UserName, UserPassword)
  Endif

  If modDatabase.$myConn.Opened = True Then
    modBasic.DebugString("App connected to " & DBName & " on Fallback Server at " & DBHost & " . Database Driver: " & CStr(modDatabase.$myConn.Version))
    ConnectionExtra()
  Else
    fmLogIn.Close
    fmLogInRE.Close
    fmLabLogIn.Close
    If Message.Warning(("Please check network connections") & "<br>" & ("1. Please check network cables.") & "<br>" & ("2. Ping To Server " & modHelpVariable.$SysMainHost), ("OK"), ("No")) = 1 Then
      Shell modApplSub.GetDeskopTerminal() & " -e \"" & "ping " & modHelpVariable.$SysMainHost & "\""
    Endif
  Endif

End

Private Sub ConnectionExtra()

  Dim UserName As String
  Dim UserPassword As String
  Dim DBName As String
  Dim DBType As String
  Dim DBHost As String
  Dim sPort As String

  If $conTarget = "Remote" Then
    DBName = $DBName
    DBType = $DBType
    DBHost = $DBHost
    UserName = $UserName
    UserPassword = $UserPassword
    sPort = $sPort
  Else
    DBName = $SysDataBase
    DBType = $SysExtService
    DBHost = $SysExtHost
    UserName = $SysExtUser
    UserPassword = $SysExtPass
    sPort = $SysExtPort
  Endif

  If sPort Then
    modDatabase.$syConn = modDBApp.OpenConnection(DBType, DBHost, DBName, UserName, UserPassword, sPort)
  Else
    modDatabase.$syConn = modDBApp.OpenConnection(DBType, DBHost, DBName, UserName, UserPassword)
  Endif
  If modDatabase.$syConn.Opened = False Then
    modDatabase.$syConn = modDatabase.$myConn
    modBasic.DebugString("Main/Fallback Server used as Read Server")
  Else
    modBasic.DebugString("App connected to " & DBName & " on Read Server at " & DBHost & " . Database Driver: " & CStr(modDatabase.$syConn.Version))
  Endif

End

Public Sub ConnectionDashboard()

  Dim UserName As String
  Dim UserPassword As String
  Dim DBName As String
  Dim DBType As String
  Dim DBHost As String
  Dim sPort As String

  ReadConfigFile()
  DBType = $SysExtService
  If DBType Then
    DBName = $SysDataBase
    DBHost = $SysExtHost
    UserName = $SysExtUser
    UserPassword = $SysExtPass
    sPort = $SysExtPort
  Else
    DBType = $SysMainService
    DBHost = $SysMainHost
    DBName = $SysDataBase
    UserName = $SysMainUser
    UserPassword = $SysMainPassword
    sPort = $SysMainPort
  Endif

  If sPort Then
    modDatabase.$syConn = modDBApp.OpenConnection(DBType, DBHost, DBName, UserName, UserPassword, sPort)
  Else
    modDatabase.$syConn = modDBApp.OpenConnection(DBType, DBHost, DBName, UserName, UserPassword)
  Endif
  If modDatabase.$syConn.Opened = False Then
    modDatabase.$myConn = modDatabase.$syConn
    modBasic.DebugString("Main/Fallback Server used as Read Server")
  Else
    modBasic.DebugString("App connected to " & DBName & " on Read Server at " & DBHost & " . Database Driver: " & CStr(modDatabase.$syConn.Version))
  Endif

End

Private Sub CreateRepositoryLocal()

  Dim sPath As String
  Dim qCon As Connection

  ' If modDatabase.$myConn.Type = "mysql" Then
  '   If Not modDatabase.$myConn.Databases.Exist("repo_" & modDatabase.$myConn.Name) Then
  '     modDatabase.$myConn.Databases.Add("repo_" & modDatabase.$myConn.Name)
  '     Message.Info(("<b>" & "Please wait...." & "</b><br>" & "Creating memory database for Data Repository"), ("OK"))
  '     qCon = modDBApp.OpenConnection("mysql", modDatabase.$myConn.Host, "repo_" & modDatabase.$myConn.Name, modDatabase.$myConn.User, modDatabase.$myConn.Password)
  '     Inc Application.Busy
  '     modDBTables.$DbFormat = "REP"
  '     modDBTables.$DbEngine = "HEAP"
  '     modDBGroup.CreateDatabaseForSish(qCon)
  '     Dec Application.Busy
  '     Try qCon.Close()
  '   Endif
  '
  ' Else
  sPath = modHelpVariable.AppDirectory &/ "repository"
  If Not Exist(sPath) Then
    modDBApp.CreateSQliteDB(sPath)
    Message.Info(("<b>" & "Please wait...." & "</b><br>" & "Creating local database for Data Repository at ") & sPath, ("OK"))
    qCon = modDBApp.OpenConnection("sqlite3", modHelpVariable.AppDirectory, "repository", "", "")
    Inc Application.Busy
    modDBTables.$DbFormat = "REP"
    modDBGroup.CreateDatabaseForSish(qCon)
    Dec Application.Busy
    Try qCon.Close()
  Endif

  ' Endif

End

Private Sub CreateLatestLocalDB()

  Dim sPath As String
  Dim qCon As Connection

  sPath = modHelpVariable.AppDirectory &/ "current"
  If Not Exist(sPath) Then
    modDBApp.CreateSQliteDB(sPath)
    Message.Info(("<b>" & "Please wait...." & "</b><br>" & "Creating local database for current schema ") & sPath, ("OK"))
    qCon = modDBApp.OpenConnection("sqlite3", modHelpVariable.AppDirectory, "current", "", "")
    Inc Application.Busy
    modDBTables.$DbFormat = "HIS"
    modDBGroup.CreateDatabaseForSish(qCon)
    Dec Application.Busy
    Try qCon.Close()
  Endif

End

Public Sub ConnectRemoteDiagnostic()

  Dim xfile As String
  Dim xdbname As String
  Dim xservice As String
  Dim xhost As String
  Dim xuser As String
  Dim xpass As String
  Dim xport As String

  xfile = modHelpVariable.GetConfigSettingFIle()
  xdbname = modControlSub.ShowSettingValue(xfile, "BillSource/Database")
  xservice = modControlSub.ShowSettingValue(xfile, "BillSource/Service")
  xhost = modControlSub.ShowSettingValue(xfile, "BillSource/Host")
  xuser = modControlSub.ShowSettingValue(xfile, "BillSource/User")
  xpass = modPassword.DecryptDBPass(modControlSub.ShowSettingValue(xfile, "BillSource/Password"), False)
  xport = modControlSub.ShowSettingValue(xfile, "BillSource/Port")
  modDatabase.$labConn = modDBApp.OpenConnection(xservice, xhost, xdbname, xuser, xpass, xport)

End

Public Sub ConnectRemotePharmacy()

  Dim xfile As String
  Dim xdbname As String
  Dim xservice As String
  Dim xhost As String
  Dim xuser As String
  Dim xpass As String
  Dim xport As String

  xfile = modHelpVariable.GetConfigSettingFIle()
  xdbname = modControlSub.ShowSettingValue(xfile, "PharmSource/Database")
  xservice = modControlSub.ShowSettingValue(xfile, "PharmSource/Service")
  xhost = modControlSub.ShowSettingValue(xfile, "PharmSource/Host")
  xuser = modControlSub.ShowSettingValue(xfile, "PharmSource/User")
  xpass = modPassword.DecryptDBPass(modControlSub.ShowSettingValue(xfile, "PharmSource/Password"), False)
  xport = modControlSub.ShowSettingValue(xfile, "PharmSource/Port")
  modDatabase.$pharmConn = modDBApp.OpenConnection(xservice, xhost, xdbname, xuser, xpass, xport)

End

'NOTE: ------------------------------------- Create error file -----------------------------------
Public Sub CreateErrorReport()

  Dim xmsg1 As String
  Dim xmsg2 As String

  If Error.Text Then
    xmsg1 = "TRANSACTION-ERROR: " & Error.Text & " [" & Error.Where & "]"
    modBasic.DebugString(xmsg1)
  Endif
  If db.Current Then
    If db.Error Then
      xmsg2 = "TRANSACTION-ERROR: Code-" & db.Error & " : " & Error.Text & " [" & Error.Where & "]"
      modBasic.DebugString(xmsg2)
    Endif
  Endif

  If modBasic.$DebugMsg = True Then
    If MMain.$IsGUIApp = True Then
      Message.Warning(xmsg1 & "<br>" & xmsg2)
    Endif
  Endif

End

Public Function GetCollectionValue(sColl As Collection, sKey As String, sParam As String) As Variant

  Dim xx As Variant

  If $conTarget = "Remote" Then
  Else
    If sParam = "Yes" Then
      If sColl Then
        If sColl.Count > 0 Then
          xx = sColl[sKey]
        Endif
      Endif
    Endif
  Endif
  Return xx

End

''ONLY FOR IRD COMPLIANCE
Public Sub RecordIRDActivity(sCon As Connection, sCategory As String, frm As String, sActivity As String, sComment As String)

  Dim res As Result
  Dim macc As String
  Dim xusr As String

  If modHelpVariable.$MACAddress Then
    Try macc = modHelpVariable.$MACAddress
  Else
    macc = ""
  Endif
  If modBasic.$lbluser Then
    Try xusr = modBasic.$lbluser
  Else
    xusr = ""
  Endif

  res = sCon.Create("tblirdactivity")
  res["fldfrmname"] = frm
  res["fldcategory"] = sCategory
  res["fldactivity"] = sActivity
  res["fldcomment"] = sComment
  res["flduserid"] = xusr
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = True
  res["fldhostmac"] = macc
  res.Update

End

Public Sub PrintLog(sLog As String)

  Dim hFile As File

  hFile = Open Desktop.CacheDir &/ modHelpVariable.AppName &/ "error.log" For Append
  For Each sLog In Split(sLog, "\n")
    Print #hFile, sLog
  Next
  Close #hFile

End
