' Gambas module file

Public Sub InstallSelectedApplication(AppList As String[])

  Dim xlist As String[]
  Dim hForm As FmTerminal
  ' Dim sPass As String

  If AppList Then
    If AppList.Count Then
      If UCase(modApplication.DistributionOSName()) = "UBUNTU" Then

        ' If MMain.$IsGUIApp = True Then
        xlist = ["sudo", "apt-get", "--no-install-recommends", "install"]
        xlist.Insert(AppList)
        hForm = New FmTerminal("Exec", xlist)
        hForm.ShowModal
        ' Else
        '   xlist = ["sudo", "apt-get", "-y", "--no-install-recommends", "install"]
        '   xlist.Insert(AppList)
        '   sPass = InputPassword(("Enter Password for Super User"), ("Super User"), "")
        '   If sPass Then
        '     modExternal.RunRootCmdAsRoot(xlist.Join(Space(1)), sPass)
        '   Endif
        ' Endif

      Endif
    Endif
  Endif

End

Public Function EssentialAppText() As String[]

  Dim xlist As String[]
  Dim xsel As String[]

  xsel = modApplication.EssenAppList()
  If xsel.Count Then
    xlist = SelectListView("Select Application to install", xsel, True)
  Endif
  Return xlist

End

Public Function OptionalAppText() As String[]

  Dim xlist As String[]
  Dim xsel As String[]

  xsel = modApplication.OptionalAppList()
  If xsel.Count Then
    xlist = SelectListView("Select Application to install", xsel, True)
  Endif
  Return xlist

End

Public Function GetFontsAllList() As String[]

  Dim xx As String
  Dim xxx As String[]

  xxx = New String[]
  For Each xx In Fonts
    xxx.Add(xx)
  Next
  Return xxx

End

Public Function GetEnvironmentList() As String[]

  Dim xx As String
  Dim xenv As String[]

  xenv = New String[]
  For Each xx In Application.Env
    xenv.Add(xx & " : " & Env[xx])
  Next
  Return xenv

End

Public Function GetGambasComponets() As String[]

  Dim sComp As Component
  Dim xx As String[]

  xx = New String[]
  For Each sComp In Components
    xx.Add(sComp.Name)
  Next
  Return xx

End

''==== ONLY FOR DESKTOP APPLICATION =====
Public Sub ConfigureDateTime()

  Dim hForm As FmTerminal

  If UCase(modApplication.DistributionOSName()) = "UBUNTU" Then
    hForm = New FmTerminal("Exec", ["sudo", "dpkg-reconfigure", "tzdata"])
    hForm.ShowModal
  Endif

End

Public Function GetDeskopTerminal() As String

  Dim aProg As String
  Dim sDesktop As String

  Try sDesktop = UCase(Desktop.Type)
  Select Case sDesktop
    Case "KDE", "KDE4", "KDE5"
      aProg = "konsole"
    Case "UBUNTU", "GNOME", "UNITY", "UBUNTU:GNOME"
      aProg = "gnome-terminal"
    Case "MATE", "CINNAMON"
      aProg = "mate-terminal"
    Case "XFCE"
      aProg = "xfce4-terminal"
    Case "LXDE"
      aProg = "lxterminal"
    Case "CYGWIN"
      aProg = "mintty.exe"
  End Select

  Return aProg

End
