' Gambas module file

''28-Oct-2016: version 0.3.12: Removing Journal Lock as it is not so (?) important and locks table several times during one procedure

Public Sub FillJournalRecord(dCateg As String, dLfno As String, cCateg As String, cLfno As String, jAmt As Float, jref As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tbljournal")
  res["flddebitcateg"] = dCateg
  res["flddebitlfno"] = dLfno
  res["fldcreditcateg"] = cCateg
  res["fldcreditlfno"] = cLfno
  res["flddate"] = Now()
  res["fldamt"] = jAmt
  res["flduserid"] = modBasic.$lbluser
  res["fldcomp"] = modBasic.$compID
  res["fldreference"] = jref
  res["xyz"] = False
  res.Update()
  'dont catch error. error will roll back

End

Public Sub InsertClaimInvoice(sBillNo As String)

  Dim res As Result

  res = modDatabase.$myConn.Create("tblbillupload")
  res["fldbillno"] = sBillNo
  res["flduserid"] = modBasic.$lbluser
  res["fldtime"] = Now()
  res["fldcomp"] = modBasic.$compID
  res["fldsave"] = True
  res["xyz"] = False
  Try res.Update

End

Public Sub InsertFiscalRangeSelected(sType As String, sRange As String)

  Dim res As Result
  Dim asx As String[]

  asx = Split(sRange, "/")
  If asx.Count = 2 Then
    res = modDatabase.$myConn.Create("tblfiscalid")
    res["fldindex"] = sRange & ":" & sType
    res["fldtype"] = sType
    res["fldlabel"] = sRange
    res["fldfrom"] = modDate.ConvertToEnglishdate(asx[0] & "/04/01")
    res["fldend"] = modDate.ConvertToEnglishdate(asx[1] & "/04/01")
    res["fldvalue"] = 1
    Try res.Update
  Endif

End

Public Sub PasInvoiceSetting(cmbinvoice As ComboBox, sFree As Boolean)

  Dim xList As New String[]

  xList = modControlSub.GetDirectFillresult(modDatabase.$myConn.Exec("select fldindex as col from tblfisclosing where (fldstate=&1 or fldstate IS NULL)", "Active"))
  xList.Add("Current")

  If sFree = True Then
    cmbinvoice.List = xList
  Else
    If modBasic.$BillPastInvoices = "Enable" Then
      cmbinvoice.List = xList
    Else
      cmbinvoice.Enabled = False
    Endif
  Endif
  cmbinvoice.Text = "Current"

End

Public Sub PasInvoiceSettingRead(cmbinvoice As ComboBox)

  Dim xList As New String[]

  xList = modControlSub.GetDirectFillresult(modDatabase.$myConn.Exec("select fldindex as col from tblfisclosing where (fldstate=&1 or fldstate IS NULL)", "Active"))
  xList.Add("Current")
  cmbinvoice.List = xList
  cmbinvoice.Text = "Current"

End
