' Gambas module file

' Public Function GetCustomDepartDemographicsVitals(dt1 As Date, dt2 As Date, sCaption As String, sDemog As String, sValue As String) As String                       ''
'
'   Dim $BillingReport As CReportHTML
'   Dim asx As New String[0]
'
'   Dim res1 As Result
'
'   $BillingReport = New CReportHTML([("Variable"), ("Male"), ("Female"), ("Total"), ("Remarks")],  "", "")
'   $BillingReport.UserData.Add("CUSTOM MEDICAL REPORT : " & sCaption, "PARAM1")
'   $BillingReport.UserData.Add("DATE: " & modReportVar.GetDateTimeReport(dt1, gb.MediumDate) & " TO " & modReportVar.GetDateTimeReport(dt2, gb.MediumDate), "PARAM2")
'
'   $BillingReport.AddChapter("Current Patients")
'
' End
