' Gambas module file

Public $APIMonth As String

Public Function GetDHISJson(xFixVar As Variant[], xTableVar As Variant[]) As Variant[]

  Dim xVar As Variant[]
  Dim aColl As Collection

  Dim xFixArry As String[]
  Dim xLabel As String
  Dim xColm As String

  Dim rowColl As Collection
  Dim xval As Variant

  xVar = New Variant[]

  For Each xFixArry In xFixVar
    xLabel = xFixArry[0]
    xColm = xFixArry[1]
    For Each rowColl In xTableVar
      If rowColl["0"] = xLabel Then
        xval = rowColl[xColm]

        If xFixArry[3] And If xFixArry[2] Then
          aColl = New Collection
          aColl.Add(xLabel & "-" & xColm, "_comment")
          aColl.Add(xFixArry[3], "categoryOptionCombo")
          aColl.Add(xFixArry[2], "dataElement")
          aColl.Add(CStr(xval), "value")
          xVar.Add(aColl)
        Endif

      Endif
    Next
  Next

  Return xVar

End

''only for safe motherhood complications
Public Function GetDHISJsonSecond(xFixVar As Variant[], xTableVar As Variant[]) As Variant[]

  Dim xVar As Variant[]
  Dim aColl As Collection

  Dim xFixArry As String[]
  Dim xLabel As String
  Dim xColm As String

  Dim rowColl As Collection
  Dim xval As Variant

  xVar = New Variant[]

  For Each xFixArry In xFixVar
    xLabel = xFixArry[0]
    xColm = xFixArry[1]
    For Each rowColl In xTableVar
      If rowColl["1"] = xLabel Then
        xval = rowColl[xColm]

        If xFixArry[3] And If xFixArry[2] Then
          aColl = New Collection
          aColl.Add(xLabel & "-" & xColm, "_comment")
          aColl.Add(xFixArry[3], "categoryOptionCombo")
          aColl.Add(xFixArry[2], "dataElement")
          aColl.Add(CStr(xval), "value")
          xVar.Add(aColl)
        Endif

      Endif
    Next
  Next

  Return xVar

End

''======================== DHIS TAGS ==========================
''dataelement,optioncombo
Public Function SetTableCellTags(sChapter As String, Optional sCategory As String) As Variant[]

  Dim aVar As Variant[]
  Dim xArr As String[]

  aVar = New Variant[]

  If sChapter = "Summary of Services" Then
    If sCategory = "Hospital Services" Then
      xArr = ["0-9 years", "1", "HscG3R78Jzc", "I1gylzOskBs"]
      aVar.Add(xArr)
      xArr = ["0-9 years", "2", "HscG3R78Jzc", "TTNFd2X49S6"]
      aVar.Add(xArr)
      xArr = ["0-9 years", "3", "XjuXeaVPUsr", "I1gylzOskBs"]
      aVar.Add(xArr)
      xArr = ["0-9 years", "4", "XjuXeaVPUsr", "TTNFd2X49S6"]
      aVar.Add(xArr)

      xArr = ["10-19 years", "1", "HscG3R78Jzc", "BsqZjzoTKXF"]
      aVar.Add(xArr)
      xArr = ["10-19 years", "2", "HscG3R78Jzc", "ayMV9ieefqQ"]
      aVar.Add(xArr)
      xArr = ["10-19 years", "3", "XjuXeaVPUsr", "BsqZjzoTKXF"]
      aVar.Add(xArr)
      xArr = ["10-19 years", "4", "XjuXeaVPUsr", "ayMV9ieefqQ"]
      aVar.Add(xArr)

      xArr = ["20-59 years", "1", "HscG3R78Jzc", "sfmUgn8yywu"]
      aVar.Add(xArr)
      xArr = ["20-59 years", "2", "HscG3R78Jzc", "iUcXHCikw4W"]
      aVar.Add(xArr)
      xArr = ["20-59 years", "3", "XjuXeaVPUsr", "sfmUgn8yywu"]
      aVar.Add(xArr)
      xArr = ["20-59 years", "4", "XjuXeaVPUsr", "iUcXHCikw4W"]
      aVar.Add(xArr)

      xArr = [">=60 years", "1", "HscG3R78Jzc", "ra6Eu2HG3uz"]
      aVar.Add(xArr)
      xArr = [">=60 years", "2", "HscG3R78Jzc", "h5jQOtCwdWf"]
      aVar.Add(xArr)
      xArr = [">=60 years", "3", "XjuXeaVPUsr", "ra6Eu2HG3uz"]
      aVar.Add(xArr)
      xArr = [">=60 years", "4", "XjuXeaVPUsr", "h5jQOtCwdWf"]
      aVar.Add(xArr)

    Else If sCategory = "Emergency Services" Then
      xArr = ["0-9 years", "1", "fuHbV1eiKs0", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["0-9 years", "2", "fuHbV1eiKs0", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["10-19 years", "1", "EtdsmjNmxVZ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["10-19 years", "2", "EtdsmjNmxVZ", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["20-59 years", "1", "CLYbMAU5lhD", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-59 years", "2", "CLYbMAU5lhD", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = [">=60 years", "1", "HEgvfxOppUY", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">=60 years", "2", "HEgvfxOppUY", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Diagnostic/Other Services" Then
      xArr = ["X-ray", "2", "RXIa0TIoAP4", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Ultrasonogram (USG)", "2", "Hy2ikWKzAUh", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Echocardiogram (Echo)", "2", "gglzlE7oJpI", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Electro Encephalo Gram (EEG)", "2", "yVhL13Rc3Gw", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Electrocardiogram (ECG)", "2", "HXPj1cIqZIC", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Trademill", "2", "aBbZ4GirNpN", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Computed Tomographic (CT) Scan", "2", "zQnc9f0Gq8Z", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Magnetic Resonance Imaging (MRI)", "2", "gT5hXh5IQ8Y", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Endoscopy", "2", "rU9EUoLmd1K", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Colonoscopy", "2", "CUrV07L8274", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Nuclear Medicine", "2", "d7xsrk6ZliX", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Total Preventive service Provided", "2", "MKLWgFA8Oyh", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Total Laboratory service Provided", "2", "UTJQ3DnKBGP", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Other Service Provided (if any)", "2", "sFkotLeU4nk", "kdsirVNKdhm"]
      aVar.Add(xArr)
    Endif

  Else If sChapter = "Summary of Indoor Services" Then
    If sCategory = "Inpatient Outcome" Then
      xArr = ["<=28 days", "1", "IEPgzf9wukn", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["<=28 days", "2", "IEPgzf9wukn", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["<=28 days", "3", "Vh884xx3SDo", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["<=28 days", "4", "Vh884xx3SDo", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["<=28 days", "5", "S74wqYPP0vX", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["<=28 days", "6", "S74wqYPP0vX", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["<=28 days", "7", "PYZpOtxWlsY", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["<=28 days", "8", "PYZpOtxWlsY", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["<=28 days", "9", "lymYBB5Td1P", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["<=28 days", "10", "lymYBB5Td1P", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["<=28 days", "11", "OyqyMUPbL5Q", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["<=28 days", "12", "OyqyMUPbL5Q", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["<=28 days", "13", "J08nUlGXWcU", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["<=28 days", "14", "J08nUlGXWcU", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["29 days-1 year", "1", "VT7pxUmkCk4", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "2", "VT7pxUmkCk4", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "3", "JjtNfeIkZc3", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "4", "JjtNfeIkZc3", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "5", "MG81K0P93cC", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "6", "MG81K0P93cC", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "7", "nAwr1SuDL5X", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "8", "nAwr1SuDL5X", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "9", "q1hEowbwEte", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "10", "q1hEowbwEte", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "11", "I9luOd2a7XZ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "12", "I9luOd2a7XZ", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "13", "u5Ju7K3EFZ3", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["29 days-1 year", "14", "u5Ju7K3EFZ3", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["1-4 years", "1", "hfKKGFpcahT", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "2", "hfKKGFpcahT", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "3", "FcYoBAZBVjO", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "4", "FcYoBAZBVjO", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "5", "BHMcr2LttVZ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "6", "BHMcr2LttVZ", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "7", "uHC49o0YWzj", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "8", "uHC49o0YWzj", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "9", "R9VsHuLaaOV", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "10", "R9VsHuLaaOV", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "11", "y9WZpRQwfwP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "12", "y9WZpRQwfwP", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "13", "W1Tfa8N3tEq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["1-4 years", "14", "W1Tfa8N3tEq", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["5-14 years", "1", "idfm34Azg6Q", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "2", "idfm34Azg6Q", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "3", "qcgMT3F0AR3", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "4", "qcgMT3F0AR3", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "5", "q1rh08vhNLa", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "6", "q1rh08vhNLa", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "7", "aFDqE1qyJwH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "8", "aFDqE1qyJwH", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "9", "i80uwDMocMV", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "10", "i80uwDMocMV", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "11", "RZxcXR28SV3", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "12", "RZxcXR28SV3", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "13", "YTzkpp1RDGx", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["5-14 years", "14", "YTzkpp1RDGx", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["15-19 years", "1", "jeODCTX57ty", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "2", "jeODCTX57ty", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "3", "VylsiKOh3Bl", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "4", "VylsiKOh3Bl", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "5", "FVUaOSyrp8X", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "6", "FVUaOSyrp8X", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "7", "HnwIe5GtEQd", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "8", "HnwIe5GtEQd", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "9", "PZP5PrfHPeK", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "10", "PZP5PrfHPeK", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "11", "J3B6Aqs64TL", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "12", "J3B6Aqs64TL", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "13", "NuvEJyyrRyn", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["15-19 years", "14", "NuvEJyyrRyn", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["20-29 years", "1", "eWZ03zEBkBX", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "2", "eWZ03zEBkBX", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "3", "bZZ5l7H5r1l", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "4", "bZZ5l7H5r1l", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "5", "qC0mnCelPuB", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "6", "qC0mnCelPuB", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "7", "oQDF5rAiZ9s", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "8", "oQDF5rAiZ9s", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "9", "OC96VpJIdoE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "10", "OC96VpJIdoE", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "11", "EHz6GfxpuXw", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "12", "EHz6GfxpuXw", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "13", "qNch4vXPvMS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["20-29 years", "14", "qNch4vXPvMS", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["30-39 years", "1", "byiU4Z8VZxP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "2", "byiU4Z8VZxP", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "3", "GwnF85IRBcP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "4", "GwnF85IRBcP", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "5", "xRGqy7Adibr", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "6", "xRGqy7Adibr", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "7", "Nifo5ju2pPP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "8", "Nifo5ju2pPP", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "9", "xOBWxJ7rtOG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "10", "xOBWxJ7rtOG", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "11", "r5ovXqoUemk", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "12", "r5ovXqoUemk", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "13", "UAbEC9wm8JC", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["30-39 years", "14", "UAbEC9wm8JC", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["40-49 years", "1", "qFKmdcMXi8R", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "2", "qFKmdcMXi8R", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "3", "a3rRLfav30P", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "4", "a3rRLfav30P", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "5", "jSCf0lQ0CKP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "6", "jSCf0lQ0CKP", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "7", "MzCbP9IShpH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "8", "MzCbP9IShpH", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "9", "GwmblUqSoMS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "10", "GwmblUqSoMS", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "11", "VDDHvT1MISE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "12", "VDDHvT1MISE", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "13", "EDHAawGus2l", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["40-49 years", "14", "EDHAawGus2l", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["50-59 years", "1", "XgqSseUwYwV", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "2", "XgqSseUwYwV", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "3", "yMvg20IXOuD", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "4", "yMvg20IXOuD", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "5", "O3Z3alM218T", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "6", "O3Z3alM218T", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "7", "IgUWH05VOXS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "8", "IgUWH05VOXS", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "9", "rvi6BdbtIu1", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "10", "rvi6BdbtIu1", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "11", "rjN2W3sO17N", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "12", "rjN2W3sO17N", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "13", "q9HWBr7XI3j", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["50-59 years", "14", "q9HWBr7XI3j", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = [">= 60 years", "1", "xsf043Abyz4", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">= 60 years", "2", "xsf043Abyz4", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = [">= 60 years", "3", "arDN0NoNYrq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">= 60 years", "4", "arDN0NoNYrq", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = [">= 60 years", "5", "GSebS9QkuVm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">= 60 years", "6", "GSebS9QkuVm", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = [">= 60 years", "7", "pjjYseu1oTW", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">= 60 years", "8", "pjjYseu1oTW", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = [">= 60 years", "9", "AbdVTngxI4X", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">= 60 years", "10", "AbdVTngxI4X", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = [">= 60 years", "11", "jvOCAVooPWG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">= 60 years", "12", "jvOCAVooPWG", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = [">= 60 years", "13", "D0BdHXhtQ0b", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = [">= 60 years", "14", "D0BdHXhtQ0b", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Maternal Age" Then
      xArr = ["<20 Yrs", "1", "LLtybn3Il5y", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["<20 Yrs", "2", "a7MLCIvl3N0", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["<20 Yrs", "3", "i4LqEvJTyyH", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["<20 Yrs", "4", "NmLTLB5IM4x", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["20-34 Yrs", "1", "Ynoi7oT6Cui", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["20-34 Yrs", "2", "jW4Nxz5ZtTc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["20-34 Yrs", "3", "T2RIoCzbcrE", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["20-34 Yrs", "4", "NNa4syq83FQ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = [">=35 Yrs", "1", "DmCnfwpVcMT", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = [">=35 Yrs", "2", "yoj2oCbvriM", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = [">=35 Yrs", "3", "bbMBbR3oQa5", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = [">=35 Yrs", "4", "KWtpxg9gMS0", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Neonate Form" Then
      xArr = ["Primi(G=1)", "1", "Iyu2jI3uZLe", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Primi(G=1)", "2", "XfaiH4LO4HU", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Primi(G=1)", "3", "J16O3bLT94B", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Primi(G=1)", "4", "Wz9lyL4EFgc", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Multi(G=1-4)", "1", "OQ4CxYP11zR", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Multi(G=1-4)", "2", "kK32tZ49ToM", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Multi(G=1-4)", "3", "Wz6fi5h43ln", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Multi(G=1-4)", "4", "f95dTxsNaOr", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Grand Multi(G>=5)", "1", "ErsRqXBszJe", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Grand Multi(G>=5)", "2", "GU5n3qxVV1G", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Grand Multi(G>=5)", "3", "FeOTYqWEND5", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Grand Multi(G>=5)", "4", "fgGIHbLGHr3", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Type of Surgeries" Then
      xArr = ["Major", "1", "MncP9cJXwZs", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Major", "2", "MncP9cJXwZs", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Major", "3", "jtiDYbqmpdM", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Intermediate", "1", "", ""]
      aVar.Add(xArr)
      xArr = ["Intermediate", "2", "", ""]
      aVar.Add(xArr)
      xArr = ["Intermediate", "3", "", ""]
      aVar.Add(xArr)

      xArr = ["Minor:Outpatients", "1", "XOIIA9PktoG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Minor:Outpatients", "2", "XOIIA9PktoG", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Minor:Outpatients", "3", "f9CFvnVSAic", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Minor:Inpatients", "1", "ds89kwFirfa", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Minor:Inpatients", "2", "ds89kwFirfa", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Minor:Inpatients", "3", "yNvksqFvO65", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Minor:Emergency", "1", "PPLkh56gSDt", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Minor:Emergency", "2", "PPLkh56gSDt", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Minor:Emergency", "3", "gGNm8ee9hl8", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Plaster", "1", "bRyy4uqVUn6", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Plaster", "2", "bRyy4uqVUn6", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Plaster", "3", "", ""]
      aVar.Add(xArr)

    Else If sCategory = "Death Information" Then
      xArr = ["Early Neonatal(0-6 days)", "1", "wE8Ua9fF57W", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Early Neonatal(0-6 days)", "2", "wE8Ua9fF57W", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["Late Neonatal(7-27 days)", "1", "i9Fd6Sg4Xvz", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Late Neonatal(7-27 days)", "2", "i9Fd6Sg4Xvz", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["Maternal (All)", "1", "OWZvJevMlQd", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Maternal (All)", "2", "", ""]
      aVar.Add(xArr)

      xArr = ["Post Operative", "1", "HUtoMj9IIHY", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Post Operative", "2", "HUtoMj9IIHY", "PflKpozpO7b"]
      aVar.Add(xArr)

      xArr = ["Others", "1", "HFWIZQsLDfa", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Others", "2", "HFWIZQsLDfa", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Free health service summary" Then
      xArr = ["Ultra Poor/Poor", "1", "fMgY7buyPgJ", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Ultra Poor/Poor", "2", "blQafu930Fk", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Ultra Poor/Poor", "3", "sboNx8FiP4d", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Ultra Poor/Poor", "4", "yeGkme7Wda5", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Helpless/Destitute", "1", "TQchxgpT1Mg", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Helpless/Destitute", "2", "K2QvU18Cy9V", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Helpless/Destitute", "3", "B9svAWSTFQt", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Helpless/Destitute", "4", "zrx6bskmDpn", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Disabled", "1", "U0aYCzqSIrV", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Disabled", "2", "oLHqNDw8P0e", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Disabled", "3", "xkfNycS7hEG", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Disabled", "4", "NoJQulKOcgB", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Sr Citizens", "1", "pGKBCQ2y96V", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Sr Citizens", "2", "FpFz27OnLjo", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Sr Citizens", "3", "wYwdmBDhBNu", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Sr Citizens", "4", "riAMS7MJ8Kz", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["FCHV", "1", "SIODC3GmBPx", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["FCHV", "2", "brA0o59G66l", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["FCHV", "3", "YLBxlWQ2Ji5", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["FCHV", "4", "pF1Mv020yUl", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Gender Based Voilence", "1", "d5xARcg2y1L", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Gender Based Voilence", "2", "WYnBzcM4iwO", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Gender Based Voilence", "3", "qLLnISVBthc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Gender Based Voilence", "4", "GnYEgVNXJ0K", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Others", "1", "xD4PTWeBft4", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Others", "2", "JT6R8JDcdm7", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Others", "3", "sSIsC8lbPDs", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Others", "4", "r46z953ZAdI", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Social Security Programme" Then
      xArr = ["Partially", "1", "XFaB9VkN3Sh", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Partially", "2", "eXUI9zdrFSY", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Completely", "1", "kpcheWPcaMi", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Completely", "2", "sT2uMMZvrSJ", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Endif

  Else If sChapter = "New Outpatient Morbidity" Then
    If sCategory = "Communicable, Immunizable" Then
      ''Measles
      xArr = ["B05", "2", "ZrwTzFTdZhz", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B05", "3", "ZrwTzFTdZhz", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Diphtheria
      xArr = ["A36", "2", "CSRB2H5GLDZ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A36", "3", "CSRB2H5GLDZ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Whooping cough
      xArr = ["A37", "2", "Y3S9491u1gd", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A37", "3", "Y3S9491u1gd", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Neonatal Tetanus
      xArr = ["A33", "2", "QQSZDRTD294", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A33", "3", "QQSZDRTD294", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Tetanus
      xArr = ["A35", "2", "qkAsR3sHGWM", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A35", "3", "qkAsR3sHGWM", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Tuberculosis
      xArr = ["A16", "2", "cVIqiRvVHVE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A16", "3", "cVIqiRvVHVE", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Acute Flaccid Paralysis
      xArr = ["G83", "2", "cSBNopxh2ZP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["G83", "3", "cSBNopxh2ZP", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Rubella
      xArr = ["B06", "2", "EJOh3U60jKx", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B06", "3", "EJOh3U60jKx", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Mumps
      xArr = ["B26", "2", "BpxwodMjTM4", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B26", "3", "BpxwodMjTM4", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Varicella [chickenpox]
      xArr = ["B01", "2", "ZJPpYiYwPeW", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B01", "3", "ZJPpYiYwPeW", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Acute hepatitis B
      xArr = ["B16", "2", "cI801zaVGau", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B16", "3", "cI801zaVGau", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Communicable, Vector Borne" Then
      ''Acute Encephalitis like Syndrome
      xArr = ["A86", "2", "pHrDUquZIYm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A86", "3", "pHrDUquZIYm", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Filariasis
      xArr = ["B74", "2", "zcypZ3frGDB", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B74", "3", "zcypZ3frGDB", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Clinical Malaria
      xArr = ["B54", "2", "QDaBpwjmfws", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B54", "3", "QDaBpwjmfws", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Malaria (Plasmodium Falciparum)
      xArr = ["B50", "2", "fZsSPCGs3d9", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B50", "3", "fZsSPCGs3d9", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Malaria (Plasmodium Vivax)
      xArr = ["B51", "2", "LZYfptKIqkh", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B51", "3", "LZYfptKIqkh", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Dengue Fever
      xArr = ["A90", "2", "XBZPrqWn6OG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A90", "3", "XBZPrqWn6OG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Kala-azar/Leshmaniasis
      xArr = ["B55", "2", "gCLElGi3gze", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B55", "3", "gCLElGi3gze", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Communicable, Water/Food Borne" Then
      ''Typhoid (Enteric Fever)
      xArr = ["A01", "2", "gwhVCfaS9UN", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A01", "3", "gwhVCfaS9UN", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Acute gastro-enteritis
      xArr = ["A09", "2", "cISG3BoGZTm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A09", "3", "cISG3BoGZTm", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Ameobic Dysentery/Amoebiasis
      xArr = ["A06", "2", "td2iBmsLero", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A06", "3", "td2iBmsLero", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Bacillary Dysentery/Shigellosis
      xArr = ["A03", "2", "y3glz39HVvQ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A03", "3", "y3glz39HVvQ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Presumed non-infectious diarrhoea
      xArr = ["K52", "2", "LAwTvVrfnOB", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K52", "3", "LAwTvVrfnOB", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Cholera
      xArr = ["A00", "2", "FJ0pdVWlBbG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A00", "3", "FJ0pdVWlBbG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Intestinal Worms
      xArr = ["B82", "2", "te3iSwrdWO7", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B82", "3", "te3iSwrdWO7", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Jaundice
      xArr = ["R17", "2", "iZDCnd0VgWy", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["R17", "3", "iZDCnd0VgWy", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Hepatitis A
      xArr = ["B15", "2", "w5mNn2EBUmg", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B15", "3", "w5mNn2EBUmg", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Hepatitis E
      xArr = ["B17", "2", "LAP6lgcrJi5", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B17", "3", "LAP6lgcrJi5", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Volume Depletion (Dehydration)
      xArr = ["E86", "2", "ZZsL7yaqg4L", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["E86", "3", "ZZsL7yaqg4L", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Other Communicable Diseases" Then
      ''Leprosy
      xArr = ["A30", "2", "zCnvG70EbAa", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A30", "3", "zCnvG70EbAa", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Meningitis
      xArr = ["G03", "2", "E80SAeiK4KF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["G03", "3", "E80SAeiK4KF", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "HIV/STI" Then
      ''HIV Infection
      xArr = ["B20", "2", "oVnNnGHesch", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B20", "3", "oVnNnGHesch", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Urethral Discharge Syndrome (UDS) Gonococal
      xArr = ["A54", "2", "B8CqXFlCBr5", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A54", "3", "B8CqXFlCBr5", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Scrotal Swelling Syndrome (SSS)
      ' xArr = ["N49", "2", ""]
      ' aVar.Add(xArr)
      xArr = ["N49", "3", "BJpAbmeRUVm", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ''Vaginal Discharge Syndrome (VDS)
      xArr = ["N89.8", "2", "HuGvgg2pOA2", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N89.8", "3", "HuGvgg2pOA2", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Lower Abdominal Pain Syndrome (LAPS)
      xArr = ["N74", "2", "uPijgtgd0jA", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N74", "3", "uPijgtgd0jA", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Neonatal Conjuctive Syndrome (NCS)
      xArr = ["A54.3", "2", "A7ZUMi18b2C", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A54.3", "3", "A7ZUMi18b2C", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Genital User Disease Syndrome (GUDS) - female
      xArr = ["N76.6", "2", "b0flJFAByeR", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ' xArr = ["N76.6", "3", ""]
      ' aVar.Add(xArr)

      ''Genital User Disease Syndrome (GUDS) - male
      ' xArr = ["N50.8", "2", ""]
      ' aVar.Add(xArr)
      xArr = ["N50.8", "3", "ru2303Sy7nA", "kdsirVNKdhm"]
      aVar.Add(xArr)

      ''Inguinal Bubo Syndrome (IBS)
      xArr = ["A55", "2", "s4WLJ0dumzx", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A55", "3", "s4WLJ0dumzx", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Syphilis
      xArr = ["A51", "2", "wxnuAwt1Hqm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A51", "3", "wxnuAwt1Hqm", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Other Infected Diseases" Then
      ''ARI/Lower respiratory tract infection (LRTI)
      xArr = ["J22", "2", "eimjIL0RFb8", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J22", "3", "eimjIL0RFb8", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Upper respiratory tract infection (URTI)
      xArr = ["J06", "2", "C1dYWXuPeBo", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J06", "3", "C1dYWXuPeBo", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Pneumonia
      xArr = ["J18", "2", "ZCcVuwqAfaG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J18", "3", "ZCcVuwqAfaG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Severe pneumonia
      xArr = ["J15", "2", "e8gE5FvXVnB", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J15", "3", "e8gE5FvXVnB", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Bronchitis (Acute & chronic)
      xArr = ["J40", "2", "G2SkThUYe5w", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J40", "3", "G2SkThUYe5w", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Urinary Tract Infection (UTI)
      xArr = ["N39", "2", "uV5LwN8OzCy", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N39", "3", "uV5LwN8OzCy", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Viral Influenza
      xArr = ["J11", "2", "qrTjnhUQ195", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J11", "3", "qrTjnhUQ195", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Reproductive Tract Infection (RTI) - Female
      xArr = ["N99", "2", "z1O4M2enpI3", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ' xArr = ["N99", "3", ""]
      ' aVar.Add(xArr)

      ''Reproductive Tract Infection (RTI) - Male
      ' xArr = ["N51", "2", ""]
      ' aVar.Add(xArr)
      xArr = ["N51", "3", "INDKIQBLb3i", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Nutritional & Metabolic Disorder" Then
      ''Goitre, Cretinism
      xArr = ["E04", "2", "Qvvn1g4XfZ1", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["E04", "3", "Qvvn1g4XfZ1", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Diabetes Mellitus (DM)
      xArr = ["E14", "2", "l09HErr6ggw", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["E14", "3", "l09HErr6ggw", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Malnutrition
      xArr = ["E46", "2", "oh9zomy0bdm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["E46", "3", "oh9zomy0bdm", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Avitaminoses & other nutrient deficiency
      xArr = ["E50", "2", "bp53MgxccqQ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["E50", "3", "bp53MgxccqQ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Obesity
      xArr = ["E66", "2", "EKavdicUQaW", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["E66", "3", "EKavdicUQaW", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Anaemia/Polyneuropathy
      xArr = ["D64", "2", "doJ6CNvMbmw", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["D64", "3", "doJ6CNvMbmw", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Polyneuritis
      xArr = ["G62", "2", "nDWUFmrIPCA", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["G62", "3", "nDWUFmrIPCA", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Skin Diseases" Then
      ''Acne
      xArr = ["L70", "2", "VAqYKbRvrHe", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L70", "3", "VAqYKbRvrHe", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Warts
      xArr = ["B07", "2", "aoQoJU7AQ9O", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B07", "3", "aoQoJU7AQ9O", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Chloasma/ melasma
      xArr = ["L81.1", "2", "ZfcANR0riP1", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L81.1", "3", "ZfcANR0riP1", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Urticaria
      xArr = ["L50", "2", "FN5uLuYjGmq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L50", "3", "FN5uLuYjGmq", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Dermatitis/Eczema
      xArr = ["L30.9", "2", "tS2cUtWNXpI", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L30.9", "3", "tS2cUtWNXpI", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Alopecia
      xArr = ["L65", "2", "DuhReYAWpjc", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L65", "3", "DuhReYAWpjc", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Vitiligo
      xArr = ["L80", "2", "Xzw4N8KPWQS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L80", "3", "Xzw4N8KPWQS", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Albinism
      xArr = ["E70.3", "2", "Xfr7s6N5ILP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["E70.3", "3", "Xfr7s6N5ILP", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Herpes simplex
      xArr = ["B00", "2", "FAaK12zZX3M", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B00", "3", "FAaK12zZX3M", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Herpes zoster
      xArr = ["B02", "2", "ZfULTbeDgRF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B02", "3", "ZfULTbeDgRF", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Erythroderma
      xArr = ["L53.9", "2", "lvrJamUsDfR", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L53.9", "3", "lvrJamUsDfR", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Impetigo
      xArr = ["L01", "2", "tdl64qm6OIo", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L01", "3", "tdl64qm6OIo", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Boils
      xArr = ["L02", "2", "DjYPzxgHx9v", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L02", "3", "DjYPzxgHx9v", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Abscess
      xArr = ["L02.0", "2", "axzMcDrcIfU", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L02.0", "3", "axzMcDrcIfU", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Furunculosis
      xArr = ["L02.9", "2", "mq1lHdw5EZ2", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L02.9", "3", "mq1lHdw5EZ2", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Fungal infection (Lichen planus)
      xArr = ["L43", "2", "rwQjknPpoey", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L43", "3", "rwQjknPpoey", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Scabies
      xArr = ["B86", "2", "txuV68xtrYc", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B86", "3", "txuV68xtrYc", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Leukoderma
      xArr = ["L81.5", "2", "JNQxHWNvhcf", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L81.5", "3", "JNQxHWNvhcf", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Psoriasis
      xArr = ["L40", "2", "ZhcOrFM8ho1", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L40", "3", "ZhcOrFM8ho1", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Acute lymphadenitis
      xArr = ["L04", "2", "IihXJC3GzYF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L04", "3", "IihXJC3GzYF", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Ear, Nose and Throat Infection" Then
      ''Acute Suppurative Otitis Media
      xArr = ["H66.0", "2", "xtYZSzBt4j8", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H66.0", "3", "xtYZSzBt4j8", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Chronic Suppurative Otitis Media
      xArr = ["H66.1", "2", "GbSRNVeeY9r", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H66.1", "3", "GbSRNVeeY9r", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Sinusitis
      xArr = ["J32", "2", "OJUFnZllsLL", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J32", "3", "OJUFnZllsLL", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Acute tonsillitis
      xArr = ["J03", "2", "Ezc8lbdvcW6", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J03", "3", "Ezc8lbdvcW6", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Pharyngitis/Sore throat
      xArr = ["J02", "2", "yFJdnwOrHXf", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J02", "3", "yFJdnwOrHXf", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Foreign body in ear
      xArr = ["T16", "2", "o2Jx5MaLlex", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["T16", "3", "o2Jx5MaLlex", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Foreign body in nose
      xArr = ["T17.1", "2", "CminYXY6RpV", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["T17.1", "3", "CminYXY6RpV", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Foreign body in throat
      xArr = ["T17.2", "2", "ek34FewqNAf", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["T17.2", "3", "ek34FewqNAf", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Wax
      xArr = ["H61.2", "2", "glyCwpl4XX3", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H61.2", "3", "glyCwpl4XX3", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Nasal polyp
      xArr = ["J33", "2", "a506kRKpXFX", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J33", "3", "a506kRKpXFX", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Deviated nasal septum (DNS)
      xArr = ["J34.2", "2", "MRSR1vwB7DR", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J34.2", "3", "MRSR1vwB7DR", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Rhinitis
      xArr = ["J31", "2", "WTmwO75ijQ0", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J31", "3", "WTmwO75ijQ0", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Otitis externa
      xArr = ["H60", "2", "iIHlesXptP0", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H60", "3", "iIHlesXptP0", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Reflux laryngitis
      xArr = ["K21.2", "2", "voyeqQ4VHCX", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K21.2", "3", "voyeqQ4VHCX", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Oral Health Related Problems" Then
      ''Dental caries
      xArr = ["K02", "2", "GyGRGTZsRHN", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K02", "3", "GyGRGTZsRHN", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Toothache
      xArr = ["K08.8", "2", "bEaNbyFhWqE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K08.8", "3", "bEaNbyFhWqE", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Periodontal disease (gum disease)
      xArr = ["K05", "2", "PGX59e9bSPx", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K05", "3", "PGX59e9bSPx", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Other disorder of teeth
      xArr = ["K08.9", "2", "xoQX7YuYQ8d", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K08.9", "3", "xoQX7YuYQ8d", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Oral ulcer (Aphthous & herpetic)
      xArr = ["K12", "2", "FZZdZbgcA47", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K12", "3", "FZZdZbgcA47", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Tooth impaction
      xArr = ["K01.1", "2", "dFlqpKxwTYh", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K01.1", "3", "dFlqpKxwTYh", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Hypoplasia
      xArr = ["K00.4", "2", "IriSNYAZb14", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K00.4", "3", "IriSNYAZb14", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Leukoplakia
      xArr = ["K13.2", "2", "OOO9AMFyOuM", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K13.2", "3", "OOO9AMFyOuM", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Fungal infection (candidiasis)
      xArr = ["B37", "2", "jXZokvGicd1", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["B37", "3", "jXZokvGicd1", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Oral space infection & abscess
      xArr = ["K04", "2", "nwdHjVGNJXP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K04", "3", "nwdHjVGNJXP", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Eye Problems" Then
      ''Conjunctivitis
      xArr = ["H10", "2", "BQhbt7KIEPW", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H10", "3", "BQhbt7KIEPW", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Trachoma
      xArr = ["A71", "2", "S6sNGnudQxv", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A71", "3", "S6sNGnudQxv", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Cataract
      xArr = ["H26", "2", "Lxyk9qE4YVm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H26", "3", "Lxyk9qE4YVm", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Blindness
      xArr = ["H54", "2", "e37wBcnOczg", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H54", "3", "e37wBcnOczg", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Refractive error
      xArr = ["H52", "2", "IqwX6ARGCF7", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H52", "3", "IqwX6ARGCF7", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Glaucoma
      xArr = ["H40", "2", "RdpEs3jOLCH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H40", "3", "RdpEs3jOLCH", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Colour blindness
      xArr = ["H53.5", "2", "zWK9OO0pMaM", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H53.5", "3", "zWK9OO0pMaM", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Exophthalmos
      xArr = ["H05.2", "2", "SzcyHRm0seg", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H05.2", "3", "SzcyHRm0seg", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Sty
      xArr = ["H00.0", "2", "K1Vggqh7EZL", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H00.0", "3", "K1Vggqh7EZL", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Chalazion
      xArr = ["H00.1", "2", "NukRpHU2mcF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H00.1", "3", "NukRpHU2mcF", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Pterygium
      xArr = ["H11.0", "2", "Bq8dxhxEmcI", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H11.0", "3", "Bq8dxhxEmcI", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Diabetic retinopathy
      xArr = ["E14.3", "2", "sMRPKqciSdG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["E14.3", "3", "sMRPKqciSdG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Hypertensive retinopathy
      xArr = ["H35", "2", "lNtBCvtTxhy", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H35", "3", "lNtBCvtTxhy", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Entropion
      xArr = ["H02", "2", "b1YXlOITj25", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H02", "3", "b1YXlOITj25", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Ectropion
      xArr = ["H02.1", "2", "p298JZkz6Ta", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H02.1", "3", "p298JZkz6Ta", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Traumatic eye disease
      xArr = ["H26.1", "2", "tnm6bH7SuJ2", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H26.1", "3", "tnm6bH7SuJ2", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Uveitis
      xArr = ["H20", "2", "mvm8Z3wTFmT", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H20", "3", "mvm8Z3wTFmT", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Macular degeneration (age related)
      xArr = ["E35.3", "2", "dHT1BRQHShX", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["E35.3", "3", "dHT1BRQHShX", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Amblyopia (Lazy eye)
      xArr = ["E53.0", "2", "KBoL28KAp3v", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["E53.0", "3", "KBoL28KAp3v", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Squint
      xArr = ["H50", "2", "LPL3KuAFTFb", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H50", "3", "LPL3KuAFTFb", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Retinitis pigmentosa
      xArr = ["H35.5", "2", "pLdnHZ6QHyu", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H35.5", "3", "pLdnHZ6QHyu", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Nightblindness/visual disturbance
      xArr = ["H53.6", "2", "Myk6XIoYftg", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["H53.6", "3", "Myk6XIoYftg", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Malignant neoplasm of eye and adnexa
      xArr = ["C69", "2", "jjYff5pdoVS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C69", "3", "jjYff5pdoVS", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Obstetrics Complications" Then
      ''Ectopic pregnancy
      xArr = ["O00", "2", "l9K5FDX0TzP", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Abortion Complication
      xArr = ["O08", "2", "l2WtbkagDEQ", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Pregnancy Induced Hypertension (PIH)
      xArr = ["O13", "2", "x6rCNsx0k94", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Severe/ Pre-eclampsia
      xArr = ["O14", "2", "EELNfz1YCZv", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Antepartum Eclampsia
      xArr = ["O15.0", "2", "SQNwhuIWZnE", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '''Intrapartum Eclampsia
      xArr = ["O15.1", "2", "AR2PUdMddYz", "kdsirVNKdhm"]
      aVar.Add(xArr)
      '''Postpartum Eclampsia
      xArr = ["O15.2", "2", "kdWPXAMCv2N", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Hyperemesis Grivadarum
      xArr = ["O21", "2", "jdMSjAAFrsr", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Antepartum Haemorrhage
      xArr = ["O46", "2", "PJklaKiPahr", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Prolonged labour
      xArr = ["O63", "2", "wOcRtQidQ51", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Obstructed Labor
      xArr = ["O64-O66", "2", "tYjWPArxgfm", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Ruptured Uterus
      xArr = ["S37", "2", "CMTTYvszId4", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Postpartum hemorrhage
      xArr = ["O72", "2", "tKnSyC5j6yR", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Retained Placenta
      xArr = ["O73", "2", "klPzarmP4i5", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Other Complications of labor and delivery
      xArr = ["O75", "2", "DHYZJyfhw1s", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Puerperal sepsis
      xArr = ["O85", "2", "daRv0ld07Hm", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Gynae Problems" Then
      ''Pelvic Inflammatory Disease (PID)
      xArr = ["N73", "2", "ZcI2ieytA1s", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Prolapsed uterus
      xArr = ["N81.4", "2", "ldgv9ph2mBj", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Menstrual disorder
      xArr = ["N92", "2", "eVXV442upyV", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Disfunctional Uterine Bleeding (DUB)
      xArr = ["N93", "2", "KRiv3u1UVbQ", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Sub- fertility (Female)
      xArr = ["N97", "2", "bQBY0ZM3U1Q", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Sub- fertility/ infertility (Male)
      xArr = ["N46", "3", "fCv76CsoGVC", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Mental Health related problems" Then
      ''Dementia
      xArr = ["F03", "2", "bPqpAal7GQR", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["F03", "3", "bPqpAal7GQR", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Addiction (ch. acoholisim, Dipsomania, drug)
      xArr = ["F10", "2", "YZoJchLc66y", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["F10", "3", "YZoJchLc66y", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Schizophrenia
      xArr = ["F20", "2", "VY580eVaGXw", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["F20", "3", "VY580eVaGXw", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Psychosis
      xArr = ["F29", "2", "AItZIQeritY", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["F29", "3", "AItZIQeritY", "PflKpozpO7b"]
      aVar.Add(xArr)

      ' ''Brief psychotic disorder
      ' xArr = ["F23", "2", ""]
      ' aVar.Add(xArr)
      ' xArr = ["F23", "3", ""]
      ' aVar.Add(xArr)

      ''Bipolar affective disorder
      xArr = ["F31", "2", "wpE1UaVVdRB", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["F31", "3", "wpE1UaVVdRB", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Depression
      xArr = ["F32", "2", "Dj1nN42wiMd", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["F32", "3", "Dj1nN42wiMd", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Phobic Anxiety
      xArr = ["F40", "2", "m09EZ409OyU", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["F40", "3", "m09EZ409OyU", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Other Anxiety
      xArr = ["F41", "2", "Gbnq9hQ8Cdv", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["F41", "3", "Gbnq9hQ8Cdv", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Obsessive - compulsive disorder
      xArr = ["F42", "2", "pmLQfrfxRGP", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["F42", "3", "pmLQfrfxRGP", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Conversive disorder (Hysteria)
      xArr = ["F44", "2", "HEHjpjSkufl", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["F44", "3", "HEHjpjSkufl", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Neurosis
      xArr = ["F48", "2", "XsxNnzlF1BX", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["F48", "3", "XsxNnzlF1BX", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Mental retardation
      xArr = ["F79", "2", "HgbiECMw5b0", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["F79", "3", "HgbiECMw5b0", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Epilepsy
      xArr = ["G40", "2", "pGgj6Uir7IQ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["G40", "3", "pGgj6Uir7IQ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Migraine
      xArr = ["G43", "2", "qJ4iFmazTlj", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["G43", "3", "qJ4iFmazTlj", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Mental illness (unspecified)
      xArr = ["F99", "2", "WVh4R6WYimN", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["F99", "3", "WVh4R6WYimN", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Malignancy" Then
      ''Breast cancer
      xArr = ["C50", "2", "foBSqZVlQqZ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C50", "3", "foBSqZVlQqZ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Cervical/ uteri cancer
      xArr = ["C53", "2", "KaHd1xBHBfO", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C53", "3", "KaHd1xBHBfO", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Lung/ brunchial Cancer
      xArr = ["C34", "2", "FvUsjP01G6w", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C34", "3", "FvUsjP01G6w", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Oesophagus cancer
      xArr = ["C15", "2", "wzTTSKR3JgH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C15", "3", "wzTTSKR3JgH", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Stomach cancer
      xArr = ["C16", "2", "CHDJ7eiK26X", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C16", "3", "CHDJ7eiK26X", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Thyroid cancer
      xArr = ["C73", "2", "qA53nDCEOgt", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C73", "3", "qA53nDCEOgt", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Liver cancer
      xArr = ["C22", "2", "Bj8m5N2pTT4", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C22", "3", "Bj8m5N2pTT4", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Pancreatic cancer
      xArr = ["C25", "2", "Ls6DBELhucD", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C25", "3", "Ls6DBELhucD", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Bone/ bone marrow cancer
      xArr = ["C79.5", "2", "RVhyQYMBoTs", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C79.5", "3", "RVhyQYMBoTs", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Gall bladder cancer
      xArr = ["C23", "2", "cWN72D91wWx", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C23", "3", "cWN72D91wWx", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Colorectal (colon with rectum) cancer
      xArr = ["C19", "2", "PYQPAx2s3On", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C19", "3", "PYQPAx2s3On", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Oral cancer
      xArr = ["C06", "2", "KkV2jvCCISU", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C06", "3", "KkV2jvCCISU", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Lymphoma cancer
      xArr = ["C85", "2", "KVZxc94qbg0", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C85", "3", "KVZxc94qbg0", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Ovary cancer
      xArr = ["C56", "2", "rorMnL90qUo", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C56", "3", "rorMnL90qUo", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Urinary bladder cancer
      xArr = ["C67", "2", "XeLKZHIMpSb", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C67", "3", "XeLKZHIMpSb", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Nasopharyngeal cancer
      xArr = ["C11", "2", "g8lF7Um9jQA", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C11", "3", "g8lF7Um9jQA", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Head & neck cancer
      xArr = ["C49.0", "2", "CFfXxPrIx8E", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C49.0", "3", "CFfXxPrIx8E", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Other Cancer
      xArr = ["C80", "2", "sO9oFKB9IAJ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["C80", "3", "sO9oFKB9IAJ", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Cardiovascular & Respiratory Related Problems" Then
      ''Hypertension
      xArr = ["I10", "2", "qrqs5BcXz4K", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["I10", "3", "qrqs5BcXz4K", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Congestive heart failure
      xArr = ["I50.0", "2", "JNDXvvL6e73", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["I50.0", "3", "JNDXvvL6e73", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Cardiac heart failure
      xArr = ["I50.9", "2", "CAgq78eCGoT", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["I50.9", "3", "CAgq78eCGoT", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Chronic Obstructive Pulmonary Disease (COPD)
      xArr = ["J44", "2", "nGRapIBn04F", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J44", "3", "nGRapIBn04F", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Acute rheumatic fever
      xArr = ["I01", "2", "bWTc0CtkExj", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["I01", "3", "bWTc0CtkExj", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Rheumatic heart disease (RHD)
      xArr = ["I09", "2", "wYzKSWInjSq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["I09", "3", "wYzKSWInjSq", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Ischemic heart disease
      xArr = ["I24", "2", "S4wji3QBoDj", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["I24", "3", "S4wji3QBoDj", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Other cardiovascular problems
      xArr = ["I52", "2", "qtjVLLOPJMq", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["I52", "3", "qtjVLLOPJMq", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Bronchial asthma
      xArr = ["J45", "2", "aeNEz2w7vUt", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J45", "3", "aeNEz2w7vUt", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Other Diseases & Injuries" Then
      ''Acute Renal failure
      xArr = ["N17", "2", "CDE0GWEcSai", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N17", "3", "CDE0GWEcSai", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Chronic Renal failure
      xArr = ["N18", "2", "r3sO6KWErru", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N18", "3", "r3sO6KWErru", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Nephritis
      xArr = ["N05", "2", "LgjEP3jIXsd", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N05", "3", "LgjEP3jIXsd", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Nephrotic syndrome
      xArr = ["N04", "2", "F9nektGalvQ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N04", "3", "F9nektGalvQ", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Headache
      xArr = ["R51", "2", "STQAKvx4hrd", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["R51", "3", "STQAKvx4hrd", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Pyrexia of Unknown Origin (PUO)
      xArr = ["R50", "2", "uuMnXAm0kdm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["R50", "3", "uuMnXAm0kdm", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Gastritis (APD)
      xArr = ["K29", "2", "PeTGehwYB0s", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K29", "3", "PeTGehwYB0s", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Insect/Wasp bite
      xArr = ["W57", "2", "AfuEmTogPN2", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["W57", "3", "AfuEmTogPN2", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Abdominal Pain
      xArr = ["R10", "2", "goDe1kKhJGF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["R10", "3", "goDe1kKhJGF", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Cirrhosis of liver
      xArr = ["K74", "2", "QXFsxDNzIa3", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K74", "3", "QXFsxDNzIa3", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Burns and Scalds
      xArr = ["T30", "2", "LFBNWB6AEAS", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["T30", "3", "LFBNWB6AEAS", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Toxic Effect
      xArr = ["T65", "2", "OqXKbJoicMI", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["T65", "3", "OqXKbJoicMI", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Dog Bite
      xArr = ["W54", "2", "hlijidCZeXC", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["W54", "3", "hlijidCZeXC", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Other rabies susceptible animal bite
      xArr = ["A82", "2", "OD3nX0vpeRk", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["A82", "3", "OD3nX0vpeRk", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Snake bite: Poisonous
      xArr = ["T63.0", "2", "ZK7kbGKuFhH", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["T63.0", "3", "ZK7kbGKuFhH", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Snake bite: Non-poisonous
      xArr = ["W59", "2", "SdnBnsRltSh", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["W59", "3", "SdnBnsRltSh", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Physical Disability (Disabled Person)
      xArr = ["Z73", "2", "lm5yM11ZfpT", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Z73", "3", "lm5yM11ZfpT", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Orthopaedic Problems" Then
      ''Falls/ injuries/ fractures
      xArr = ["T14", "2", "VBrz7cTB79f", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["T14", "3", "VBrz7cTB79f", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Road Traffic Accident (RTA)
      xArr = ["V89", "2", "wmZ2OGp6ukm", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["V89", "3", "wmZ2OGp6ukm", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Rheumatoid arthritis
      xArr = ["M06", "2", "NNlu3dspuAb", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["M06", "3", "NNlu3dspuAb", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Arthritis
      xArr = ["M13", "2", "zcqze4wzYJf", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["M13", "3", "zcqze4wzYJf", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Osteo arthrosis
      xArr = ["M19", "2", "rHbb3KBlxBU", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["M19", "3", "rHbb3KBlxBU", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Back ache (musculo- skeletal pain)
      xArr = ["M54.9", "2", "PABYQLhP6kF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["M54.9", "3", "PABYQLhP6kF", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Surgical Problems" Then
      ''Acid peptic disorders
      xArr = ["K27", "2", "YCXYzdxUeum", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K27", "3", "YCXYzdxUeum", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Anal Fissure
      xArr = ["K60.2", "2", "jdsiabr6R8B", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K60.2", "3", "jdsiabr6R8B", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Anal fistula
      xArr = ["K60.3", "2", "INV87zUyfus", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K60.3", "3", "INV87zUyfus", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Fistula of Intestine
      xArr = ["K63.2", "2", "OJRkVtEJZJA", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K63.2", "3", "OJRkVtEJZJA", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Renal stones
      xArr = ["N20.0", "2", "sOXBvbQfg3k", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N20.0", "3", "sOXBvbQfg3k", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Breast lumps (adenoma)
      xArr = ["N63", "2", "iiJsrZe0bNk", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N63", "3", "iiJsrZe0bNk", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Mastitis (Ignored breast)/breast abscess
      xArr = ["N61", "2", "fi0vtzIViQE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N61", "3", "fi0vtzIViQE", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Mastalgia breast
      xArr = ["N64.4", "2", "asmWrHpopvG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N64.4", "3", "asmWrHpopvG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Lumps (lipoma)
      xArr = ["D17", "2", "ba2N6S0Nqdb", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["D17", "3", "ba2N6S0Nqdb", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Sebaceous cyst
      xArr = ["L72.1", "2", "ctGjkbCRtZn", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["L72.1", "3", "ctGjkbCRtZn", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Pilonidal sinus
      xArr = ["J32", "2", "ZhUGMCZfdWb", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["J32", "3", "ZhUGMCZfdWb", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Appendicitis
      xArr = ["K37", "2", "NM4bzwrsgs0", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K37", "3", "NM4bzwrsgs0", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Cholecystitis
      xArr = ["K81", "2", "QxEgmIN7OQM", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K81", "3", "QxEgmIN7OQM", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Cholelithiasis (gall stone)
      xArr = ["K80", "2", "A6x6SS5Dgds", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K80", "3", "A6x6SS5Dgds", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Hernia
      xArr = ["K46", "2", "Wtjpt7S9YQG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["K46", "3", "Wtjpt7S9YQG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Hydrocoele
      xArr = ["N43", "2", "y0eNCU4p6nf", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N43", "3", "y0eNCU4p6nf", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Phimosis/para-phimosis
      xArr = ["N47", "2", "DEtuUddCtlE", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N47", "3", "DEtuUddCtlE", "PflKpozpO7b"]
      aVar.Add(xArr)

      '''Haemorrhoids/Piles
      xArr = ["I84", "2", "WEEGs3oAxHz", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["I84", "3", "WEEGs3oAxHz", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Epididymitis/ Orchitis
      xArr = ["N45", "2", "so2s568hmR9", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N45", "3", "so2s568hmR9", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Prostatism (BEP/BPH)
      xArr = ["N41", "2", "Y5tTcY8S6tG", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["N41", "3", "Y5tTcY8S6tG", "PflKpozpO7b"]
      aVar.Add(xArr)

      ''Not mentioned above and other
      xArr = ["R69", "2", "G0FIKc60DcJ", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["R69", "3", "G0FIKc60DcJ", "PflKpozpO7b"]
      aVar.Add(xArr)

    Endif

  Else If sChapter = "Safe Motherhood Programme" Then
    If sCategory = "Delivery Type" Then
      xArr = ["Spontaneous", "1", "VdZyJrLrSg5", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Spontaneous", "2", "rqny3AJuymt", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Spontaneous", "3", "c6dLz049UWw", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Vacuum/Forcep", "1", "CtX7O3pbtL3", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Vacuum/Forcep", "2", "fQU35FONgPq", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Vacuum/Forcep", "3", "NdY1V8YqJDd", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Surgery", "1", "BoPXsSKiPVx", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Surgery", "2", "xAulrqfseew", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Surgery", "3", "zgNUMf4qP2Z", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Delivery Outcome" Then
      xArr = ["Total Mothers", "1", "UQTYGjWr7wz", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Total Mothers", "2", "cMo5gmSt1yV", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Total Mothers", "3", "pP3HfFu4Bte", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Live Baby(Female)", "1", "Yjwho2iruhu", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Live Baby(Female)", "2", "w0fvdvU1yuF", "ye1QuAMRG5Z"]
      aVar.Add(xArr)
      xArr = ["Live Baby(Female)", "3", "ZtwhYCiEQ7w", "ye1QuAMRG5Z"]
      aVar.Add(xArr)

      xArr = ["Live Baby(Male)", "1", "Yjwho2iruhu", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Live Baby(Male)", "2", "w0fvdvU1yuF", "PflKpozpO7b"]
      aVar.Add(xArr)
      xArr = ["Live Baby(Male)", "3", "ZtwhYCiEQ7w", "PflKpozpO7b"]
      aVar.Add(xArr)

    Else If sCategory = "Birth Weight" Then
      xArr = ["Normal(>=2.5Kg)", "1", "uzX1NG6xDwr", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Normal(>=2.5Kg)", "2", "DjglomjSiAu", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Normal(>=2.5Kg)", "3", "vIuy5zKUj82", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Low(1.5-2.5Kg)", "1", "r1x2daA3pwt", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Low(1.5-2.5Kg)", "2", "stOtnhrYX9J", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Low(1.5-2.5Kg)", "3", "ssjLchkxrC3", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Very Low(<1.5Kg)", "1", "uGteAfUfOBk", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Very Low(<1.5Kg)", "2", "DFEHOcOqW5a", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Very Low(<1.5Kg)", "3", "zaFinXSR0UY", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Delivery Service" Then
      xArr = ["SBA", "1", "T9SHzXzpwnJ", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["SBA", "2", "GmSYhnEFEPr", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Non SBA", "1", "WyIabPquKV4", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Non SBA", "2", "CddyVd7FKmr", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Stillbirth" Then
      xArr = ["Fresh Still Birth", "1", "k2StfxOzXpx", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Macerated Still Birth", "1", "FlyYBxnmKup", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "ANC Services" Then
      xArr = ["ANC: 1st Visit", "1", "C6ubEqEew8X", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["ANC: 1st Visit", "2", "kSnqP4GPOsQ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["ANC: 4th Month", "1", "vH9Mm6o3LKn", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["ANC: 4th Month", "2", "Bf3ebOgYXFL", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Four check ups", "1", "RtidqFs7NRc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Four check ups", "2", "gNcAqChA90J", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "PNC Visit" Then
      xArr = ["PNC: 1st Visit (in 24 Hours)", "1", "b8jGBrMfBbP", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Three check ups", "1", "Aw24Ejbp63F", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Obstetric Complications" Then
      ''Ectopic pregnancy
      xArr = ["O00", "2", "f4ueiBTKF1T", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Abortion complication
      xArr = ["O08", "2", "S4CFTXyEFVc", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Preg.-induced hypertension
      xArr = ["O13", "2", "JLKFv7K2i7Y", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Severe/Pre-eclampsia
      xArr = ["O14", "2", "v3zKVR5wJt3", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Eclampsia
      xArr = ["O15", "2", "PELChUNfW2C", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Hyperemesis grivadarum
      xArr = ["O21.0", "2", "LIo3j809JrK", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Antepartum haemorrhage
      xArr = ["O46", "2", "ueBJTsv0PXr", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Prolonged labour
      xArr = ["O63", "2", "wsncKYDcmqr", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Obstructed Labor
      xArr = ["O64-O66", "2", "Dior21jcQCe", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Ruptured uterus
      xArr = ["S37.6", "2", "nwQoDUhFR1z", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Postpartum haemorrhage
      xArr = ["O72", "2", "PGNd6jcxJX4", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Retained placenta
      xArr = ["O73", "2", "kV3JhKJWMR8", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Pueperal sepsis
      xArr = ["O85", "2", "dHet49ySm06", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ''Other complications
      xArr = ["O75", "2", "XAzAbTRbJve", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Transfusion Done" Then
      xArr = ["Female", "1", "UUZw688ThWK", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Female", "1", "r0HLdqmLwFB", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Maternal Death in Hospital" Then
      xArr = ["Number", "1", "YZfwWNZzfg0", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Number", "2", "BL5XaUOJ6aw", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Number", "3", "IMFPhLtATaw", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "Incentive" Then
      xArr = ["ANC Incentive", "1", "dZo1PDWPAO1", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["ANC Incentive", "2", "ysTJteUVzO1", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Transport Incentive", "1", "MO4VQOLebuG", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["Transport Incentive", "2", "ua0pnAingEU", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Endif

  Else If sChapter = "Laboratory Services" Then
    If sCategory = "HAEMATOLOGY" Then
      xArr = ["Hb", "2", "MX5XthyOLIX", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["RBC Count", "2", "ga8cotZYUGN", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["TLC", "2", "udHP9cMdus0", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Platelets Count", "2", "HkVFI7zvtco", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["DLC", "2", "Ks9ADEZCFQd", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["ESR", "2", "hcN0jcWCBLx", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["PCV/Hct", "2", "saptNmjMs1t", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["MCV", "2", "o6paypYS2tc", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["MCH", "2", "kTMrl2nmqdQ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["MCHC", "2", "mucJ3LkNOGi", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["RDW", "2", "jtq2eCYU4TI", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Blood Group & Rh Type", "2", "sgR3aHSyj0A", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Coombs test", "2", "V2rLFh947Xk", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Retics", "2", "XJcUhKfv6iG", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["PBS/PBF", "2", "IB7pwInGJ2Z", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["HbA1c", "2", "TPfANsOsI68", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Special Stain(MPO)", "2", "JWcZvHhr1Wh", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Special Stain(PAS)", "2", "JaZYiW0YaCW", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Sickling Test", "2", "TWkqsR5UgVd", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Urine for Hemosiderin", "2", "KhBNHEeaRQ6", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["BT", "2", "PEtNspPKfGU", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["CT", "2", "VxCaWebcSNY", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["PT-INR", "2", "hvKJZhQvtlD", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["APTT", "2", "lQ3GQrEk9mB", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Bone Marrow Analysis", "2", "I8Z2E4Kmgii", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Aldehyde test", "2", "QPNEYl5SKm8", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["MP Total", "2", "UX2IdkwZPm6", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Smear MP Pos(PF)", "2", "nTOEK8miG0K", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Smear MP Pos(PV)", "2", "LZPBP5dgWs0", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Smear MP Pos(P-MIX)", "2", "myzTAYlWVAc", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["MF", "1", "TVZ5CT66epd", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["MF", "2", "r25JvgKGqwE", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["LD Bodies", "2", "dkU2y8nxG0h", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Hb Electrophoresis", "2", "F8v1z9J0lOg", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["LE cell", "2", "RdQOc3LQLP7", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["ALC", "2", "MT1F817ybIC", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["AEC", "2", "rkRPuVmJri8", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["FDP", "2", "bwHADypDLFl", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["D-dimer", "2", "roqaipUwNjT", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Fac VIII", "2", "vBnEHWgBcLR", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Fac IX", "2", "UK3UTayMDhQ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Others", "2", "ksFMz4c0I39", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "IMMUNOLOGY" Then
      xArr = ["Pregnancy Test (UPT)", "2", "R5coLEZO6gu", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["ASO", "2", "rwRnTLpdCWu", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["CRP", "2", "biBCfb3VTLe", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["RA Factor", "2", "NHUktqhJjbE", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["TPHA", "1", "KQGrcNYhocs", "wCvNkhhbSbl"]
      aVar.Add(xArr)
      xArr = ["TPHA", "2", "KQGrcNYhocs", "A0ezJDD4TfL"]
      aVar.Add(xArr)

      xArr = ["ANA", "2", "nkd4WEiWYpm", "A0ezJDD4TfL"]
      aVar.Add(xArr)

      xArr = ["Anti-dsDNA", "2", "nOITz2nNxAs", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["RPR/VDRL", "1", "mhrHV87Zc9U", "kdsirVNKdhm"]
      aVar.Add(xArr)
      xArr = ["RPR/VDRL", "2", "llvGO9epm7O", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["CEA", "2", "Chpshc4ebjM", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["CA-125", "2", "gVibsIFUGKo", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["CA-19.9", "2", "Y75eapME064", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["CA-15.3", "2", "wt7S2uqK6K1", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Toxo", "2", "vbl1CwVTr6v", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Rubella", "2", "RBHRqI1plDF", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["CMV", "2", "kbaZJco7mAo", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["HSV", "2", "YEgSZqDWUNm", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Measles", "2", "SJZ1Uv3fXPn", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Echinococcus", "2", "lv5WiRQ4EeS", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Amoebiasis", "2", "ZCoqqsa2dPi", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["PSA", "2", "U8KGjwMF8pn", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Ferritin", "2", "ZD0rMCtnrmu", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Cysticercosis", "2", "dRgsrcHnY6k", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Brucella", "2", "lrfHXRRnECT", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Thyroglobulin", "2", "uYVS9Y6WGGX", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Anti TPO", "2", "nmdxncyFWLp", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Protein Electrophoresis", "2", "ys3Z6SrXbl8", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Anti-CCP", "2", "hg6gptvIanY", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["RK-39", "1", "Vjdjtgx1vez", "wCvNkhhbSbl"]
      aVar.Add(xArr)
      xArr = ["RK-39", "2", "Vjdjtgx1vez", "A0ezJDD4TfL"]
      aVar.Add(xArr)

      xArr = ["JE", "1", "zebx7lWQoyM", "wCvNkhhbSbl"]
      aVar.Add(xArr)
      xArr = ["JE", "2", "zebx7lWQoyM", "A0ezJDD4TfL"]
      aVar.Add(xArr)

      xArr = ["Dengue", "1", "ci7ny20DDx5", "wCvNkhhbSbl"]
      aVar.Add(xArr)
      xArr = ["Dengue", "2", "ci7ny20DDx5", "A0ezJDD4TfL"]
      aVar.Add(xArr)

      xArr = ["Rapid MP test", "1", "B5ykil1xCD7", "kdsirVNKdhm"]
      aVar.Add(xArr)
      ' xArr = ["Rapid MP test", "1", "uxXLme8h5rp", "kdsirVNKdhm"]
      ' aVar.Add(xArr)
      xArr = ["Rapid MP test", "2", "FxeXI2YccuG", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Mantoux test", "2", "iR2RIlfklv4", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Chikungunya", "1", "mWOLG4uhHKF", "wCvNkhhbSbl"]
      aVar.Add(xArr)
      xArr = ["Chikungunya", "2", "mWOLG4uhHKF", "A0ezJDD4TfL"]
      aVar.Add(xArr)

      xArr = ["Scrub Typhus", "2", "IlNmTeeBikM", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["H. Pylori", "2", "ruFgBQtcLeT", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Leptospira", "2", "ST5xRwmGRmQ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Others", "2", "W7hA38opoJo", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "BIOCHEMISTRY" Then
      xArr = ["Sugar", "2", "GYgsh4jyQhD", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Blood Urea", "2", "zEyNSH7f3bc", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Creatinine", "2", "EAej1kE1URL", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Sodium (Na)", "2", "gCtmVdbe7SY", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Potassium (K)", "2", "KkBUEB0zQPc", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Calcium", "2", "R5LM4KpJvod", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Phosphorus", "2", "FNACMSYVtoH", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Magnesium", "2", "K1sYUht3jjV", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Uric acid", "2", "aZL9j6tqQ9p", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Total Cholesterol", "2", "wulw5ifRsNe", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Triglycerides", "2", "aSL8XQRSfQp", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["HDL", "2", "EDGJSDQRSBc", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["LDL", "2", "VXTX6a2cthA", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Amylase", "2", "jnhUYbBZse7", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Micro albumin", "2", "BdUuj8ytHYt", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Bilirubin", "2", "APPyfaSy6hf", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["SGPT", "2", "uk6zFeOqUKH", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Alk Phos", "2", "iKAc48pZwIU", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["SGOT", "2", "a0yIeDftBG7", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Total Protein", "2", "n5icJ65j8Q3", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Albumin", "2", "KxjvbnzwCwh", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Gamma GT", "2", "FrhqMwAiYdj", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["24hr urine protein", "2", "C7eoJAFCH0M", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["24hr urine U/A", "2", "zl0PSyO6WQx", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Creatinine Clearance", "2", "Wqf9ZelXBdQ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Iron", "2", "ExnjpyTiZkk", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["TIBC", "2", "w1CqsqkUyl8", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["CPK-MB", "2", "i0ymcWrlIw3", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["CPK-NAC", "2", "Ikff1OUhABP", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["LDH", "2", "u1gdmCfIfGa", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Iso-Trop-I", "2", "oGlhaIup37P", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Others", "2", "RqSKEolefFR", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "BACTERIOLOGY" Then
      xArr = ["Gram stain", "2", "coBAbfppycX", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Culture (Blood)", "2", "it4JusH87Wk", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Culture (Urine)", "2", "sLACvSMlg2x", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Culture (Body Fluid)", "2", "xMXbKs6edeu", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Culture (Swab)", "2", "MkoyR8apLNJ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Culture (Stool)", "2", "llI4WtU0scF", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Culture (Water)", "2", "mV5BSo4BMEk", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Culture (Pus)", "2", "kp79HNscnxJ", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Culture (Sputum)", "2", "dXK9lQSnxrg", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Culture (CSF)", "2", "gvv8uQaWTcW", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Culture (Others)", "2", "BcUCgFWFJBe", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Sputum AFB", "2", "iHLe8HKsB3K", "A0ezJDD4TfL"]
      aVar.Add(xArr)

      xArr = ["Other AFB", "2", "sgUz4KSpNIA", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Leprosy Smear", "2", "Lruh22ELAGR", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["India Ink Test", "2", "Av4WfkcxAQA", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Fungus(KOH Test)", "2", "Ko8Z7R3PaN2", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Fungus(Culture)", "2", "KaPqUD0bWdd", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Others", "2", "VTEmZoEWvp1", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "VIROLOGY" Then
      xArr = ["HIV", "1", "HJpcsC6D0at", "wCvNkhhbSbl"]
      aVar.Add(xArr)
      xArr = ["HIV", "2", "HJpcsC6D0at", "A0ezJDD4TfL"]
      aVar.Add(xArr)

      xArr = ["HAV", "1", "SsCz3Z9wUvx", "wCvNkhhbSbl"]
      aVar.Add(xArr)
      xArr = ["HAV", "2", "SsCz3Z9wUvx", "A0ezJDD4TfL"]
      aVar.Add(xArr)

      xArr = ["HBsAg", "1", "X8FtE4lSQYQ", "wCvNkhhbSbl"]
      aVar.Add(xArr)
      xArr = ["HBsAg", "2", "X8FtE4lSQYQ", "A0ezJDD4TfL"]
      aVar.Add(xArr)

      xArr = ["HCV", "1", "AETUEJEkhGk", "wCvNkhhbSbl"]
      aVar.Add(xArr)
      xArr = ["HCV", "2", "AETUEJEkhGk", "A0ezJDD4TfL"]
      aVar.Add(xArr)

      xArr = ["HEV", "1", "WmSJOvBs3Ck", "wCvNkhhbSbl"]
      aVar.Add(xArr)
      xArr = ["HEV", "2", "WmSJOvBs3Ck", "A0ezJDD4TfL"]
      aVar.Add(xArr)

      xArr = ["Anti-HBs", "2", "xcxZPAxhCrT", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["HBeAg", "2", "dVvGXhFywu7", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Anti-HBe", "2", "X5nw2T7NV8r", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["HBcAg", "2", "BZIy8aFttCi", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Anti-HBcAg", "2", "T4Q5ABFtjDP", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Western blot", "2", "HQr6MM8GsjH", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["CD4 count", "2", "ujt1GxVHLHV", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Viral load", "2", "DcQtyLaLoCx", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Others", "2", "vmRFuQZTS6N", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "PARASITOLOGY" Then
      xArr = ["Stool R/E", "2", "b3zYEkHFmat", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Occult blood", "2", "z9i5nhshIPk", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Reducing sugar", "2", "aydXkBquvXP", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Urine R/E", "2", "PX30ls6pIRm", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Bile salts", "2", "KC4gQ1lbXAg", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Bile pigments", "2", "uVcWLuam362", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Urobilinogen", "2", "XEe49IIPcoD", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Porphobilinogen", "2", "pZSos4N7N2Y", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Acetone", "2", "W1DQovLs4sh", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Chyle", "2", "rzfTpDSCtgk", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Specific Gravity", "2", "rhxy310LFSm", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Bence Jones protein", "2", "cGHCgAKZnjR", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Semen analysis", "2", "SXwweKinsnK", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Others", "2", "uWALxnktvW8", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "HORMONE/ENDOCRINE" Then
      xArr = ["T3", "2", "LzXPUrRvir7", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["T4", "2", "WqsPscUDVDk", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["TSH", "2", "QsKf27NOrBI", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Cortisol", "2", "qHhZNumTNcz", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["AFP", "2", "vdMAkrFTc6e", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["b-HCG", "2", "HtBLiECACGI", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["LH", "2", "W7tq5I1K1BO", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["FSH", "2", "rUL3GChBDhn", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Prolactin", "2", "c0JMi1fDGqe", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Oestrogen", "2", "V8mAXNggfSP", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Progesterone", "2", "o6U9cg57pSH", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Testosterone", "2", "GOMZ5qZQVs7", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Vit.D", "2", "ad7l9UXQ95i", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Vit.B12", "2", "W58gwBA5MiV", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Others", "2", "O2l3vMZAkYD", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "DRUG ANALYSIS" Then
      xArr = ["Carbamazepine", "2", "mMckO2ciFc8", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Cyclosporine", "2", "dSvjfeY3o91", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Valporic acid", "2", "Buc8Fke2SMT", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Phenytoin", "2", "d6EvPlKfJLX", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Digoxine", "2", "gBGJ7ghPg92", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Tacrolimus", "2", "rolQymvE0V7", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Others", "2", "aFxFDDT7Oaf", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "HISTOPATHOLOGY/CYTOLOGY" Then
      xArr = ["Biopsy(H & E)", "2", "CLAPaXEhw5K", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Biopsy(Other)", "2", "GavlUw7f7UO", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Cytology(Pap)", "2", "U2jRar05uYB", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Cytology(Giemsa)", "2", "CqTFn3gaaxt", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Cytology(Others)", "2", "NjfwcREF9Ro", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Else If sCategory = "IMMUNO-HISTO CHEMISTRY" Then
      xArr = ["ER", "2", "G2cxwinrrRA", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["PR", "2", "QAKH6RCErmb", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["G-FAP", "2", "OAX1MLXQ5JV", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["s-100", "2", "eMDAo089gz3", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Vimentin", "2", "V89xWqV2EGN", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Cytokeratin", "2", "AhRD9oaSjeL", "kdsirVNKdhm"]
      aVar.Add(xArr)

      xArr = ["Others", "2", "kZZRJEecl4i", "kdsirVNKdhm"]
      aVar.Add(xArr)

    Endif

  Endif

  Return aVar

End
