' Gambas module file

Public $AyurvedicDiagnosis As String
Public $AMISFreeServices As String[]
Public $AMISConsultTypes As String[]
Public $AMISIPServiceList As String[]

Public $AMISPurvaKarma As String[]
Public $AMISUpaKarma As String[]
Public $AMISPradhanKarma As String[]
Public $AMISTherapYoga As String[]

Private $OpdVisitColl As Collection
Private $IPservicesColl As Collection
Private $FreeHealthColl As Collection

Public $PurvaUpaKarmaColl As String[]
Public $PradhanKarmaColl As String[]
Public $TherapyYogaColl As String[]
Public $KsarSutraColl As String[]

Public Sub LoadAMISLists()

  $AMISFreeServices = ["Ultra Poor/Poor", "Helpless/Destitute", "Disabled", "Sr Citizens", "FCHV", "Gender Based Violence", "Others"]
  $AMISConsultTypes = ["General Treatment", "Purvakarma", "Upakarma", "Pradhankarma", "Ksharsutra", "Therapeutic Yoga", "Elderly Service", "Lactating Mother & Baby"]
  $AMISIPServiceList = ["General Medicine", "General Surgery", "Paediatrics", "Obstetric", "Gynecology", "ENT", "Orthopedics", "Psychiatric", "Dental"]

  $AMISPurvaKarma = ["Dipan/Pachan", "Internal Shrehan", "External Shrehan", "Ekanga Swedan", "Swarnga Swedan"]
  $AMISUpaKarma = ["Sthanik Basti", "Pichu", "Potli sweda", "Shirodhara", "Achitparna", "Other"]
  $AMISPradhanKarma = ["Vamana", "Virechana", "Matra Basti", "Anuvasan Basti", "Mustadi Basti", "Guduchyadi Basti", "Pichha Basti", "Vaitaran Basti", "Other Basti", "Nasya", "Raktamokshana"]
  $AMISTherapYoga = ["Suchma Vyayam", "Aasan", "Pranayam", "Shatkarma", "Dhyaan", "Other"]

End

Public Sub GetAMISCollection()

  $OpdVisitColl = New Collection
  $IPservicesColl = New Collection
  $FreeHealthColl = New Collection

End

Public Sub ClearAMISCollection()

  $OpdVisitColl.Clear()
  $IPservicesColl.Clear()
  $FreeHealthColl.Clear()

End

Public Sub GetAgeGroupingAMIS() As String[]

  Dim xx As String[]

  xx = New String[]
  xx.Add("<=6 months;0;180")
  xx.Add("6 months-1 year;181;364")
  xx.Add("1-4 years;365;1824")
  xx.Add("5-9 years;1825;3649")
  xx.Add("10-19 years;3650;7299")
  xx.Add("20-59 years;7300;21899")
  xx.Add(">= 60 years;21900;730000")

  Return xx

End
