' Gambas module file

Public Function GetMLModelsList() As String[]

  Dim i As Integer
  Dim xxx As String[]

  xxx = New String[]
  For i = 1 To 20
    If modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "Name") Then
      xxx.Add(modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "Name"))
    Endif
  Next
  Return xxx

End

Public Function GetModelValue(encid As String, xModel As String, Optional sFile As String) As String

  Dim i As Integer
  Dim xargs As String
  Dim xurl As String
  Dim xcmd As String

  Dim asx As String[]
  Dim xx As String
  Dim xvar As Variant
  Dim xVarLst As String[]

  Dim aData As String[]
  Dim xval As String

  For i = 1 To 20
    If modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "Name") = xModel Then
      xargs = modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "Arguments")
      xurl = modSettings.ShowModelsSettingFromFIle("Model" & CStr(i) & "/" & "URL")
      Break
    Endif
  Next

  aData = New String[]
  aData.Add("--form 'model=" & Quote(xModel) & "'")

  If xargs Then
    asx = Split(xargs, ";")
    xVarLst = New Variant[]
    For Each xx In asx
      xvar = modReportVar.GetPatientVariableValue(xx, encid)
      If xvar Then
        If xvar = "__" Then
        Else
          xVarLst.Add(CStr(xvar))
        Endif
      Endif
    Next

    aData.Add("--form 'args=" & Quote(xVarLst.Join(",")) & "'")
  Endif

  If sFile Then
    aData.Add("--form 'files=@" & Quote(sFile) & "'")
  Endif

  If xurl Then
    xcmd = "curl --location " & xurl & "?upload" & Space(1) & aData.Join(Space(1))
    modBasic.DebugAPIString(xcmd)
    Shell xcmd To xval
  Endif

  Return xval

End
