' Gambas module file

Private hTaskStart As StartUpScript
Private hTaskClose As ClosingScript
Private hTaskAdvert As AdvertiseTask
Private hTaskDBLog As DBLogTask
Private hTaskDbUpload As DataUploadTask
Private hTaskDBLocalUpload As DataLocalUploadTask
Private hTaskImgUpload As ImgUploadTask
Private hTaskDocUpload As DocUploadTask
Private hTaskPacsUpload As PacsUploadTask
Private hSyncPatient As DataPatSyncTask

''Repo
Private hTaskStoreUpload As DataUploadStoreTask
Private hTaskClinicUpload As DataUploadClinicTask
Private hTaskCashUpload As DataUploadCashTask

Public $PacsNode As String
Public $PacsModality As String

Public $DocTableID As Long
Public $RemoteUser As String
Public $RepoPatNo As String
Public $RepoEncID As String

'NOTE: ---------------------------- SPECIAL SCRIPTS -------------------------------------------
Public Sub CloseAllTasks()

  If hTaskAdvert Then
    hTaskAdvert.Stop
    hTaskAdvert = Null
  Endif

  If hTaskDBLog Then
    hTaskDBLog.Stop
    hTaskDBLog = Null
  Endif

  If hTaskDbUpload Then
    hTaskDbUpload.Stop
    hTaskDbUpload = Null
  Endif

  If hTaskDBLocalUpload Then
    hTaskDBLocalUpload.Stop
    hTaskDBLocalUpload = Null
  Endif

  If hTaskImgUpload Then
    hTaskImgUpload.Stop
    hTaskImgUpload = Null
  Endif

  If hTaskDocUpload Then
    hTaskDocUpload.Stop
    hTaskDocUpload = Null
  Endif

  ''Repo
  If hTaskStoreUpload Then
    hTaskStoreUpload.Stop
    hTaskStoreUpload = Null
  Endif

  If hTaskClinicUpload Then
    hTaskClinicUpload.Stop
    hTaskClinicUpload = Null
  Endif

  If hTaskCashUpload Then
    hTaskCashUpload.Stop
    hTaskCashUpload = Null
  Endif

  If hSyncPatient Then
    hSyncPatient.Stop
    hSyncPatient = Null
  Endif

  Wait

End

'--------------------------------------
Public Sub ExecStartUpScript()

  If hTaskStart = Null Then hTaskStart = New StartUpScript As "StartTask"

End

Public Sub StartTask_Read(Data As String)

  Print Data

End

'----------------------------------------------
Public Sub ExecClosingScript()

  If hTaskClose = Null Then hTaskClose = New ClosingScript As "CloseTask"

End

Public Sub CloseTask_Read(Data As String)

  Print Data

End

''-------------------------------------------------
Public Sub GetAdvertiseData()

  If hTaskAdvert = Null Then hTaskAdvert = New AdvertiseTask As "AdvertTask"

End

Public Sub AdvertTask_Read(Data As String)

  Print Data

End

''----------------------------------------------------
Public Sub GetRemoteDBLog()

  If hTaskDBLog = Null Then hTaskDBLog = New DBLogTask As "RemoteDbLogTask"

End

Public Sub RemoteDbLogTask_Read(Data As String)

  Print Data

End

''-----------------------------------------------
Public Sub GetDataLocalRepositoryUploader()

  If hTaskDBLocalUpload = Null Then hTaskDBLocalUpload = New DataLocalUploadTask As "DBLocalUploadTask"

End

Public Sub DBLocalUploadTask_Read(Data As String)

  Print Data

End

''----------------------------------------------
Public Sub GetDataRepositoryUploader()

  If hTaskDbUpload = Null Then hTaskDbUpload = New DataUploadTask As "DBUploadTask"

End

Public Sub DBUploadTask_Read(Data As String)

  Print Data

End

''---------------------------------------------------
Public Sub GetImgRepositoryUploader()

  If hTaskImgUpload = Null Then hTaskImgUpload = New ImgUploadTask As "ImgRepoUploadTask"

End

Public Sub ImgRepoUploadTask_Read(Data As String)

  Print Data

End

''------------------------------------------------
Public Sub GetDocRepositoryUploader(sDocID As Long, sUser As String, sPatNo As String, sEncid As String)

  $DocTableID = 0
  $RemoteUser = ""
  $RepoPatNo = ""
  $RepoEncID = ""
  If sDocID And If sUser Then
    $DocTableID = sDocID
    $RemoteUser = sUser
    $RepoPatNo = sPatNo
    $RepoEncID = sEncid
    If hTaskDocUpload = Null Then hTaskDocUpload = New DocUploadTask As "DocRepoUploadTask"
  Endif

End

Public Sub DocRepoUploadTask_Read(Data As String)

  Print Data

End

''------------------------------------------
Public Sub GetPacsRepositoryUpload(sNode As String, sModality As String)

  $PacsNode = ""
  $PacsModality = ""
  If sNode And If sModality Then
    $PacsNode = sNode
    $PacsModality = sModality
    If hTaskPacsUpload = Null Then hTaskPacsUpload = New PacsUploadTask As "PacsRepoUploadTask"
  Endif

End

Public Sub PacsRepoUploadTask_Read(Data As String)

  Print Data

End

''------------------Store ----------------------------
Public Sub GetStoreRepositoryUploader()

  If hTaskStoreUpload = Null Then hTaskStoreUpload = New DataUploadStoreTask As "StoreUploadTask"

End

Public Sub StoreUploadTask_Read(Data As String)

  Print Data

End

''------------------clinic ----------------------------
Public Sub GetClinicRepositoryUploader()

  If hTaskClinicUpload = Null Then hTaskClinicUpload = New DataUploadClinicTask As "ClinicUploadTask"

End

Public Sub ClinicUploadTask_Read(Data As String)

  Print Data

End

''------------------Account ----------------------------
Public Sub GetAccountRepositoryUploader()

  If hTaskCashUpload = Null Then hTaskCashUpload = New DataUploadCashTask As "CashUploadTask"

End

Public Sub CashUploadTask_Read(Data As String)

  Print Data

End

''------------------------ Patient data sync --------------------
Public Sub GetPatRepositorySync(sPatNo As String)

  $RepoPatNo = ""
  If sPatNo Then
    $RepoPatNo = sPatNo
    If hSyncPatient = Null Then hSyncPatient = New DataPatSyncTask As "PatientSyncTask"
  Endif

End

Public Sub PatientSyncTask_Read(Data As String)

  Print Data

End
