' Gambas module file

Public $NeuroTwin As String[] = ["Cranial Nerves", "Upper Proximal Motor Power", "Upper Distal Motor Power", "Sensory Function C5", "Sensory Function C6", "Sensory Function C7", "Sensory Function C8", "Finger-Nose Test", "Bicep Jerk", "Tricep Jerk", "Supinator Jerk", "FLAIR", "FABER", "Lower Proximal Motor Power", "Lower Distal Motor Power", "EHL", "FHL", "Sensory Function L2", "Sensory Function L3", "Sensory Function L4", "Sensory Function L5", "Sensory Function S1", "Sensory Function S2", "Heel-Shin Test", "Knee Jerk", "Ankle Jerk", "Straight Leg Raise Test", "Plantar Response"]

Public Function GetNeurologyReport(encid As String, sExamName As String, sHash As String, sType As String) As String

  Dim $BillingReport As CReportHTML
  Dim asx As New String[0]
  Dim i As Integer
  Dim res As Result

  Dim examList As String[]
  Dim xexam As String
  Dim examdual As String
  Dim xval As String
  Dim sColl As Collection

  examdual = sExamName & " [Two-sided Examinations]"
  examList = ["Presenting Complaints", "GCS", "MMSE", "Nystagmus", "Neck Rigidity", examdual, "Cervical Spine", "Thoracic Spine", "Lumbar Spine", "Sacrococcygeal Spine", "Tandem Gait"]
  $BillingReport = New CReportHTML([("SNo"), ("Variable"), ("Value")], "PatientReport", encid)
  $BillingReport.UserData.Add(sExamName, "Report")
  $BillingReport.UserData.Add(modReportVar.GetDateTimeReport(Now(), gb.GeneralDate), "PARAM1")

  sColl = New Collection
  res = modDatabase.$syConn.Exec("select fldid,fldhead,fldoption,fldtype,fldrepquali,fldrepquanti,fldtime from tblpatientexam where fldencounterval=&1 and fldfilepath=&2 and fldinput=&3", encid, sHash, sType)
  If res.Available Then
    For Each res
      If res["fldhead"] = "GCS" Then
        xval = modClinic.GetExamValueSubString(res["fldid"], encid)
      Else If res["fldhead"] = "MMSE" Then
        xval = res["fldrepquali"] & " [" & res["fldrepquanti"] & "]"
      Else If res["fldhead"] = examdual Then
        xval = modClinic.GetExamValueSubString(res["fldid"], encid)
      Else
        xval = res["fldrepquali"]
      Endif
      sColl.Add(xval, res["fldhead"])
    Next
  Endif

  i = 1
  For Each xexam In examList
    With asx
      .Add(CStr(i))
      .Add(xexam)
      If xexam = "Presenting Complaints" Then
        .Add(modPatPatho.ShowSelectedHistoryValue(encid, "General Complaints"))
      Else
        .Add(sColl[xexam])
      Endif
    End With
    $BillingReport.Add(asx)
    asx.Clear()
    i = i + 1
  Next

  Return $BillingReport.NewHTMLPath()

End
